### ISSUE TITLE
Dynamic lane selection causes trains to get stuck

### ISSUE THREAD

**Issue by namyzarc2** [CitiesSkylinesMods/TMPE#1034]
### Describe the problem
It appears that TM:PE has a bug which causes trains to get stuck at the edge of the map. With dynamic lane selection turned up, trains will sometimes try to enter the map on the same lane as trains trying to leave the map. this causes a backup that is difficult or impossible to clear. 

### Steps to reproduce

1. Turn up Dynamic lane selection. I do not know the exact percentage that dynamic lane selection needs to be turned up to, in order to get the bug to happen, but it seems like the higher the percentage the more likely it is to happen.
2. Have some cargo train terminals - not sure if their quantity, location or which side of the track they are on makes a difference, but in two of my maps that this has happened to, I had two or more of them.
3. Wait.... eventually a train will try to enter the map from the same track that another train is trying to exit.

Can be fixed by using a map editing tool to separate incoming/outgoing tracks into single lane tracks.

**Comment by krzychu124** [comment]
Interesting, I must check, but it sounds weird 🤔

**Comment by aubergine10** [comment]
Are you sure it was an incoming train on an outgoing track?

The problem I usually see with trains getting stuck at edge of map is due to the segment at map edge being too short. If I extend the segment (the one at the outside connection) to be longer than the train, using Move It mod, the trains no longer get stuck at the edge. The segment should be longer than your longest cargo/passenger train (the segment at edge is acting like a station track, hence the `X` crossover rails at the end of it) - if a train is longer than station track, game gets confused and train can get stuck for some time causing 'train jam'.

**Comment by krzychu124** [comment]
See response above, explains one of known causes of that issue. TM:PE DLS does not affect trains at all so it's impossible to be the cause.
