### ISSUE TITLE
trams are unable to turn based on lane arrows on shared car-tram lanes.

### ISSUE THREAD

**Issue by WildQuoll** [CitiesSkylinesMods/TMPE#1053]
### Describe the problem
TMPE appears to apply overly strict restrictions on trams changing lanes on junctions, preventing tram lines from be placed in situations where it shouldn't.

In this example I've got a 4-lane 2-way road with tram tracks running down the middle (https://steamcommunity.com/sharedfiles/filedetails/?id=2130577793) and the Snowfall DLC 2-lane 1-way road with tram track:
![1](https://steamuserimages-a.akamaihd.net/ugc/1750181096995468925/519C7A3282E90CC8C6AB6CB1AFDEE2BA23C1DA32/)

I am placing a tram stop on the 4-lane 2-way road (on the right), and then attempting to place the next stop on the 2-lane road. As you can see, the game won't let me to:
![2](https://steamuserimages-a.akamaihd.net/ugc/1750181096995467543/8EAEA6A0719CB1DBD406930CF0F4C8DD9B7231C3/)

I am guessing TMPE is forbidding all vehicles using the left lane on the 4-lane road from entering the right lane on the 2-lane road. While this makes sense for cars, this restriction should not be applied to trams.

The issue does *not* occur if the 4-lane road is replaced with a similar road, where the central lanes are tram only (https://steamcommunity.com/sharedfiles/filedetails/?id=2130576379).

The issue only occurs when using TMPE.

### Steps to reproduce
1.  Build a junction like on the screenshot using the 4L 2-way road with tram tracks (https://steamcommunity.com/sharedfiles/filedetails/?id=2130577793) and the Snowfall DLC 2L 1-way road with tram track.
2. Place a tram stop on the 4L road.
3. Attempt to place the next tram stop on the 2L road. Notice that the game will refuse to connect them.

**Comment by krzychu124** [comment]
Hi, have you tried enabling "Allow lane change at junction" option? 
It's interesting problem and I'll take a look what is going on there.

**Comment by WildQuoll** [comment]
I have tried that option, it didn't make any difference.

I have also tried "Busses may ignore lane arrows" in case that applied to trams as well, but also no luck.

**Comment by krzychu124** [comment]
It's can be temporarily fixed using lane connector tool, but I'll try to improve current lane routing algorithm to cover similar cases

**Comment by RLemonache** [comment]
There is such a problem when connecting trams into roundabouts as well. They will not ignore lane arrows, making it impossible for them to stay in the roundabout to make a u-turn. I think I can work around this issue, but it would be fantastic if I didn't have too, since many tram roads position them on shared lanes with cars. 
![TMPE Trams](https://user-images.githubusercontent.com/49251607/144115826-c9befbfe-6b65-4c4c-877c-6b6c72aebab9.png)
Here is an example, I illustrated the lane arrows in gray, the dotted line is the intended path.
The purple line is the alternative path using the center of the roundabout for tram specific roads, which would force the use of traffic lights at the junction, being obviously less than ideal...
I'll take any suggestions on how to fix this, if there are any, thanks!

**Comment by kianzarrin** [comment]
Interestingly trams will not turn right only when there is a right turn arrow!
![image](https://user-images.githubusercontent.com/26344691/160239497-3c3aebca-882b-443c-9b35-1f03d414306c.png)
```cs
if (applyHighwayRules || // highway rules enabled
	(nextIncomingDir == ArrowDirection.Right && hasLeftArrow) || // valid incoming right
	(nextIncomingDir == ArrowDirection.Left && hasRightArrow) || // valid incoming left
	(nextIncomingDir == ArrowDirection.Forward && hasForwardArrow) || // valid incoming straight
	(nextIncomingDir == ArrowDirection.Turn && canTurn) /*valid turning lane*/) 
{
	// matching arrow for law obiding cars
	isCompatibleLane = true;
	transitionType = LaneEndTransitionType.Default;
} else if (nextIsConnectedWithPrev) {
	// no matching arrow for SOS/reckless/trams
	transitionType = LaneEndTransitionType.Relaxed;
	if (numNextRelaxedTransitionDatas < MAX_NUM_TRANSITIONS) {
		nextRelaxedTransitionDatas[
			numNextRelaxedTransitionDatas++].Set(
			nextLaneId,
			nextLaneIndex,
			transitionType,
			nextSegmentId,
			isNodeStartNodeOfNextSegment,
			GlobalConfig.Instance.PathFinding.IncompatibleLaneDistance /*2*/);
	}
}
```

**Comment by kianzarrin** [comment]
Damn this is also influenced by the lane arrows of the non-tram lane!
![image](https://user-images.githubusercontent.com/26344691/160240012-37acc4ff-1547-414a-bbb4-e936552c0103.png)

**Comment by kianzarrin** [comment]
@aubergine10 do you know all the issues with regard to mixed train/car lanes?
so far I know of these:
on mixed car/tram lanes:
1- good: normal cars are only restricted by lane arrows (bus,  SOS, and  reckless cars ignore lane arrows as usual).
2- good: trams are only restricted by turn angle.
3- bad: cars have similarLaneIndex == 0 which might encourage them to turn into outer-most lane instead of the inner-most lane. (any issue associated with this?)
4- trams are confused too by lane arrows for some reason (probably AI). [this issue]
5- bad: cannot set lane connection for trams/cars separately [#354]
6- bad: tracked vehicles spend time calculating the turn angle. this could be cached.

5 and 6 can be fixed if I mark lane transitions for car/track. 
Is that right? any other problem I missed?

**Comment by aubergine10** [comment]
> 1- good: normal cars are only restricted by lane arrows (bus, SOS, and reckless cars ignore lane arrows as usual).

Bus should only ignore lane arrows if the relevant option is set in mod options. Same for evacuation buses.

Another thing, although I've not yet determined the cause, is that sometimes buses will go off their _route_ (they'll travel along different road even though no bus _route_ on that road). Next time in game I'll try and get some screenshots to illustrate and create issue for that.

**Comment by ian76g** [comment]
> Another thing, although I've not yet determined the cause, is that sometimes buses will go off their _route_ (they'll travel along different road even though no bus _route_ on that road). Next time in game I'll try and get some screenshots to illustrate and create issue for that.

Reason:
Sometimes a firetruck is "working" on the route of the bus - so the regular road/route is blocked. The bus then drives a "detour" arround the firemen dousing a fire.... nice feature!

**Comment by aubergine10** [comment]
> Reason: Sometimes a firetruck is "working" on the route of the bus - so the regular road/route is blocked. The bus then drives a "detour" arround the firemen dousing a fire.... nice feature!

No, this wasn't caused by the `Blocked` flag. They were routinely going off-route and the only way I could stop them doing it was to add vehicle restrictions and reduce speed of road.
