### ISSUE TITLE
Lane connectors to buildings like warehouses

### ISSUE THREAD

**Issue by cabadam** [CitiesSkylinesMods/TMPE#1133]
### Describe your idea
Is there a way to use TM:PE's lane control functionality to indicate that a particular lane should ONLY be used to enter (and I suppose exit?) a building such as the cargo train terminal or warehouses?

Consider the situation where you have a 6-lane (3 each direction) road with a warehouse next to it.  I would like to indicate that the rightmost lane (next to the warehouse) is used only for turning in/out of the warehouse.  Thru traffic should keep to the left lanes.

You can kind of simulate this by moving the warehouse off of that road with a one-way road branching off and rejoining after, but that takes up a lot more space (which in my present use case I don't have due to other railways / roads next to it).

### Screenshots?
In this screenshot, a couple logging trucks are holding up a whole line of other vehicles that have no need to be in that lane.
![image](https://user-images.githubusercontent.com/11012233/124643761-13c30100-de57-11eb-966c-e2fa9654debe.png)

**Comment by yackimoff** [comment]
FYI, you can use lane arrow tool on the first intersection after the building to switch off any direction for the rightmost lane, in which case the pathfinder won't consider this lane for cars going through, but the lane will remain preferable for cars going to buildings near that lane.

In my understanding using lane connection tool to connect to buildings is not possible at least because it's a middle of a segment and a building you want to connect whereas the tool operates on nodes.

**Comment by krzychu124** [comment]
Not possible due to road network data structure and pathfinding limitations.
