### ISSUE TITLE
Revive LABS workshop page for 11.6 testing?

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1205]
And update changelog, milestones, etc., to list all the stuff since... May 2020?

**Comment by krzychu124** [comment]
Dang, long time no see 😄 _(you are still in our internal group on discord 😉 )_

Hmm, I've created [TM:PE TEST](https://steamcommunity.com/sharedfiles/filedetails/?id=2489276785) since we've had to test a lot of things, like complete migration to Harmony which finally fixes issues on Linux #817 although TEST is still marked as `unlisted` on WS because I didn't want to create too much attention because of not much free time to respond to issues (now is much better)

**Comment by DaEgi01** [comment]
I'd rather take it private for the time beeing so that users of the current test version don't have to switch again and all others are not confused by its presence. we can revive it when krzy takes a long vacation :)
