### ISSUE TITLE
TMPE doesn't save settings changes after I quit game

### ISSUE THREAD

**Issue by Thaodon** [CitiesSkylinesMods/TMPE#1206]
### Describe the problem
I'm changing settings in game in TMPE menu, than I start new game and it's all fine, all changed settings stay, also when I quit back to main menu they stay. But after I quit game and start it again all settings are reset to default.
I've uninstalled game, deleted all files which I could find saves etc., installed new game, disabled all mods, only TMPE was activ, started new map and it still keeps reseting settings. TM:PE version 11.5.2

### Steps to reproduce
I'm changing these:
- Simulation accuracy to medium - to medium
- Customisations come in to effect immediately - on
- Disable despawning - on
- Advanced Vehicle AI - on and around 70%
- Busses may ignore lane arrows - on
- Automatically add traffic lights if applicable - off
- Ban private cars and trucks on bus lanes - on
- Heavy trucks prefer outer lanes on highways on

### Log files
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/7613790/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/7613791/output_log.txt)

### Savegame?
https://steamcommunity.com/sharedfiles/filedetails/?id=2667186106

**Comment by krzychu124** [comment]
Could you post logs (TMPE + output_log.txt) **after** you try to save game? Those you've posted are from main menu, and game is clearing log files each time you start it, so load/start new game, do something (create lane connection/set priority rules/ whatever) and just save game, then get both logs.

Oh.. I think I see what you are trying to do. Settings you select in the mod options in the main menu are not saved anywhere (as mentioned in the warning dialog that should pop in). You have to start new game or load savegame, change settings and save game, because all settings are stored inside the savegame so you can have completely different configuration for each savegame if you want.

**Comment by Thaodon** [comment]
Oh I get it now! I misunderstood the message. Damn such a newb mistake. Thanks for help!

**Comment by krzychu124** [comment]
I have plans to either hide some settings or add a feature to pull settings from selected savegame when new game started (not decided yet and also I don't have much time :/ ).

**Comment by aubergine10** [comment]
Tagging #363

**Comment by aubergine10** [comment]
Closing this - follow #363 for updates.
