### ISSUE TITLE
Split out delivery vans, cargo trucks, and tractors

### ISSUE THREAD

**Issue by VictorPhilipp** [CitiesSkylinesMods/TMPE#141]
"I love the vehicle restrictions.. But it would be beneficial to allow commercial deliveries and still block tractors and / or industrial cargo trucks."

see http://steamcommunity.com/workshop/filedetails/discussion/583429740/1318835718951055747/

**Comment by VictorPhilipp** [comment]
Could we add the bike's circulation on the lanes of cars? It would be more realistic and especially useful with the "Bike Ban On Sidewalks".
In theory, could we also add trams to the list of selectable vehicles? I know this would pose a visual problem in which you don't wish to interfere: therefore, it is only a theoretical question.

**Comment by VictorPhilipp** [comment]
Precision on the circulation of bicycles on roadways: the road editor made it possible with a lane "mixed". However, the result does not seem satisfactory: circulations are not synchronized and bicycles and cars overlap.

**Comment by VictorPhilipp** [comment]
The ability to have mixed lanes (e.g. for bicycles and cars) would have to be implemented by CO, not by TMPE.

**Comment by aubergine10** [comment]
Tagging #42

**Comment by hoclun-rigsep** [comment]
"love the vehicle restrictions.. But it would be beneficial to allow commercial deliveries and still block tractors and / or industrial cargo trucks."

I agree... would make it easier to establish cargo terminals just for one or the other. But what is the difference in this context between 'tractor' and 'industrial cargo truck'?

Thank you for all your work!

**Comment by aubergine10** [comment]
> ...it would be beneficial to allow commercial deliveries and still block tractors and / or industrial cargo trucks."
> 
> ...would make it easier to establish cargo terminals just for one or the other.

Love the idea of resource-specific terminals, but it's not in scope of TM:PE; rather than adding more complexity to pathfinder, it would be much better implemented as a mod to Transfer Manager AI and work similar to Industries DLC warehouses. I'll create an issue in [mod wishlist](https://github.com/CitiesSkylinesMods/CitiesSkylinesModWishList).

**Comment by aubergine10** [comment]
[No Big Trucks](https://steamcommunity.com/sharedfiles/filedetails/?id=2069057130) mod probably a better approach vs. more cumbersome vehicle restrictions UI and pathfinder changes... should #141 be closed?

**Comment by aubergine10** [comment]
Or integrate with "big truck" flag in AVO, and have cargo restriction a tri-state (deny, any cargo, small cargo)?

**Comment by krzychu124** [comment]
I would close this issue, as it is outside of TMPE scope

**Comment by hoclun-rigsep** [comment]
I am not convinced it is out of scope: the game physically models interactions among vehicles on the road and the distinction being called for in this issue is that between the form factors of the vans on the one hand and tractor-trailer cargo trucks on the other.

**Comment by krzychu124** [comment]
AI is the same (that's what we check), +vans don't have trailers, the difference might be in `ItemClass`, which describes service(25), subservice(36) and level (5), but there is a chance (didn't check) that the vans use the same ItemClass as tractor+trailer :/

**Comment by aubergine10** [comment]
IIRC any vehicle can have a trailer, for example this [disaster van with trailer](https://steamcommunity.com/sharedfiles/filedetails/?id=2639691768):

![image](https://user-images.githubusercontent.com/1386719/143791770-bfb81dd5-465b-45b2-bb76-562fd9237ffb.png)

And this [Fiat 500 passenger car with caravan trailer](https://steamcommunity.com/sharedfiles/filedetails/?id=708807833):

![image](https://user-images.githubusercontent.com/1386719/143791962-f1270d25-555b-4a5c-ac31-b0c1f672472a.png)

And this [oversized road train](https://steamcommunity.com/sharedfiles/filedetails/?id=2528138252) - this is one vehicle with 3 trailers (just a big gap between the leading escort car and the truck cabin):

![image](https://user-images.githubusercontent.com/1386719/143792021-cb5a1cf0-b9ac-4aeb-b8fc-51b8212783d5.png)

One possible issue is that trailers don't seem to be properly categorised in some cases? You can see in AVO mod, and also [discussed in this AVO issue](https://github.com/CityGecko/CS-AdvancedVehicleOptions/issues/19). For example, sometimes "bendy bus" trailers are appearing in the farming category, etc.

For me the biggest issue with filtering at the pathfinder level is that it is just ripe for causing pathing problems in large cities. There's no way yet for TM:PE to alert a user "this cargo can't reach destination because you banned it from using the routes it needs to take".

The "No Big Truck" mod has been working fine for me so far, it's largely eradicated big trucks turning up in places I don't want them, _it sends small trucks instead_ - and that's the key point here; if we prevent big trucks in the pathfinding stage, then the destination is deemed unreachable - the delivery won't be made at all.

With No Big Trucks mod, so long as there's a decent alternate route for big trucks to use, they will use it. I'm currently building a bypass road along a river to a small ship port, and the big trucks use that (faster speed) bypass road all the time. I've not had any snaking through the small town even though the main road though that town is a shorter route for the trucks. (excuse grim image quality, i'm mid-way through changing all my eyecandy mod settings):

![image](https://user-images.githubusercontent.com/1386719/143792620-c1bedb18-079c-436f-a3ff-b698ec69c31a.png)

**Comment by krzychu124** [comment]
Yeah, almost all vehicles can have trailers and the reason you see Farming industry trailers for everything is that is the easiest way to create new trailer -> you need trailer template, there is no car trailer one, but you can use Farming tractor trailer (available in vanilla). Most likely asset creators forgot to change item class before saving.

**Comment by aubergine10** [comment]
Maybe AVO or some other mod could find a way to work out which trailers belong to which vehicles and then set trailer to same AI class as the vehicle? Although... is it possible for more than one vehicle to use the same trailer?
