### ISSUE TITLE
Missing timed traffic lights and manual traffic lights buttons

### ISSUE THREAD

**Issue by NateNate60** [CitiesSkylinesMods/TMPE#1423]
### Describe the problem

The buttons for timed traffic lights and manual traffic lights are not present in the UI.

### Steps to reproduce

1. Disable all mods except for TM:PE and Harmony.
2. Create a new map in the asset editor consisting of a single two-lane highway outside connection and a small hole containing a water source. This is the bare minimum that fits the map requirements.
3. Save the map and publish it in the New Game menu
4. Exit to the main menu
5. Start a new game from the map just created
6. Open TM:PE to notice that the time traffic lights and manual traffic lights buttons are missing.

### Log files

[Player.log](https://github.com/CitiesSkylinesMods/TMPE/files/8100721/Player.log)

### Screenshots?

![Screenshot from 2022-02-18 14-03-36](https://user-images.githubusercontent.com/41277019/154767423-bf59c3b0-9632-4fb6-a323-7e4c51c46ed3.png)

### Notes or questions?

I'm running TM:PE 11.6.4.8 Stable on Ubuntu Linux 21.10. Game is launched through Steam.

**Comment by krzychu124** [comment]
Go to options, Maintenance tab, enable Timed Traffic lights

**Comment by aubergine10** [comment]
Hmm... I think the issue might be that we disable TTL mod option when entering asset editor, and maybe that somehow that persists when loading a savegame in same session? I'll check as I work through #1356 tasks.

**Comment by aubergine10** [comment]
@NateNate60 Did enabling traffic lights in options > TM:PE > Maintenance solve the problem in-game? Does the option get reset if you use editor before loading a save?

**Comment by krzychu124** [comment]
Traffic lights switch off when you enter Asset/map editor, but should switch back to on if you had it enabled while saving game last time. Maybe auto-enable does not work as expected 🤔 We need to check that.

**Comment by aubergine10** [comment]
@NateNate60 Could you try going in to map editor, save the map, then start a new city with that map and see if the traffic lights are turned off again? If so, that would indicate the issue is TM:PE saving the disabled traffic light setting in map, and cities started from that map are loading the settings stored in the map (in which case PR #1425 should solve that issue).

**Comment by krzychu124** [comment]
@aubergine10 but we are reading TTL settings from the savegame every time 🤔

**Comment by aubergine10** [comment]
@krzychu124 Maps are savegames, just tagged "Map" instead of "Savegame", IIRC?

BTW, I suspect lots of weird stuff exists in workshop maps (just like that time one of the CO maps had loads of red cars waiting to park...). I know back in early days of Traffic++ there was [a bug that deposited broken stuff in maps](https://steamcommunity.com/sharedfiles/filedetails/changelog/409184143?p=2) (see `Update: 22 May, 2015 @ 6:02pm` section).

**Comment by aubergine10** [comment]
> @aubergine10 but we are reading TTL settings from the savegame every time 🤔

A new city created from a map = bascially the map _is_ the savegame at that point. We check to see if options exist in whatever it is that was loaded and if so use them. Prior to TM:PE 11.6.x the mod would always be completely inactive in editors; so this could be an issue that's been brewing since we added editor support - it could be storing mod options, etc., in to the actual map in the editor, which are then loaded whenever a new city is started from that map.

Note in OP:

> 5 Start a new game from the map just created

**Comment by aubergine10** [comment]
actually, wait, I see where problem could be...

**Comment by aubergine10** [comment]
Ok, so we set the default values _in `Options.cs`_ like so:

```csharp
        public static bool prioritySignsEnabled = true;
        public static bool timedLightsEnabled = true;
        public static bool customSpeedLimitsEnabled = true;
        public static bool vehicleRestrictionsEnabled = true;
        public static bool parkingRestrictionsEnabled = true;
        public static bool junctionRestrictionsEnabled = true;
        public static bool turnOnRedEnabled = true;
        public static bool laneConnectorEnabled = true;
```

When someone loads map editor, the `timedLightsEnabled` are forced false. That is to say, `Options.timedLightsEnabled = false`.

So someone starting new game without exiting to desktop now defaults to traffic lights beuing disabled.

In my work on #1356 I'm setting things up so that all defaults are defined in `OptionsManager.LoadData()` which would resolve that issue - see point 4 in 1356:

![image](https://user-images.githubusercontent.com/1386719/154779010-7edfa8ad-916b-4d4a-9d04-5551dfe86a51.png)
