### ISSUE TITLE
Include a Collection for quick review

### ISSUE THREAD

**Issue by vwspeedracer** [CitiesSkylinesMods/TMPE#1437]
### Describe your idea

Consider creating and maintaining a Workshop Collection for each of these broken item sets so that people can find out if they're subscribed to any of them at a quick glance, and unsubscribe from all of them with a single click.

### Screenshots?

N/A

### Notes or questions?

here's a great example of someone having doing this for Prop Anarchy
https://steamcommunity.com/sharedfiles/filedetails/?id=2756408312

**Comment by aubergine10** [comment]
Does it really matter considering every government on the planet is gearing up for another round of global democide?

**Comment by snowflitzer** [comment]
This idea is already done. Check the workshop mate. Look for LemonG

 

From: vwspeedracer ***@***.***> 
Sent: Friday, 25 February 2022 7:11 AM
To: CitiesSkylinesMods/TMPE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CitiesSkylinesMods/TMPE] Include a Collection for quick review (Issue #1437)

 


Describe your idea


Consider creating and maintaining a Workshop Collection for each of these broken item sets so that people can find out if they're subscribed to any of them at a quick glance, and unsubscribe from all of them with a single click.


Screenshots?


N/A


Notes or questions?


here's a great example of someone having doing this for Prop Anarchy
https://steamcommunity.com/sharedfiles/filedetails/?id=2756408312

**Comment by vwspeedracer** [comment]
(Not sure what global politics has to do with Cities:Skylines, but ok I guess?)

Perhaps then modify this request to actually providing a link to the collections on the Broken items pages for easier access?

**Comment by aubergine10** [comment]
State funded terrorists are heros, apparently.

**Comment by vwspeedracer** [comment]
I'm sure your engagement with GitHub feature requests will save the day.

**Comment by aubergine10** [comment]
don't forget to wave your skycloth at the state funded terrorists as they bomb cities all over the world
