### ISSUE TITLE
"Speed limits stuck at intersections" - user report

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#1439]
Looks like an issue with CSUR roads where speed limit tool not working on intersections (specifically the speed icon is shown but it is not interactive).

![image](https://user-images.githubusercontent.com/1386719/155858299-a5f55d54-4539-4601-b98d-4f9c506dceab.png)

![image](https://user-images.githubusercontent.com/1386719/155858303-ad9b2b80-4c3a-4fba-a06a-47651a0eafa3.png)

![image](https://user-images.githubusercontent.com/1386719/155858309-057ac006-b5a0-47bb-94dd-38be9146b3f2.png)

Video: https://www.bilibili.com/video/BV1JF411t7ZR/

Savegame: https://steamcommunity.com/sharedfiles/filedetails/?id=2765776220

**Comment by krzychu124** [comment]
I'm not sure but to me it looks like TM:PE shift thingy caused an infinite loop, it was reported and fixed some time ago, but Kian changed my lazy fix "abort collecting segments when already added" to math solution calculating angles etc, which still does not work.
I'll test and try to find what is wrong

**Comment by krzychu124** [comment]
It's a bug in GetNodeSegmentIds enumerator. Due to how CSUR roads are connected it can stuck in infinite loop. Normally it takes right segment in relation to a shared node each iteration and if the next one is equal to the initial segment it stops iteration, but.... on CSUR roads game can return the same segment as "right" asking for start or end node, so you will get segment X, then Y and then right from Y will be X... 
To me it looks like a bug, either in vanilla or in CSUR. 
GetRightSegment method is used in PF but each iteration is guarded with a counter check (less than 8).

**Comment by DaEgi01** [comment]
i am going to check it out :)
