### ISSUE TITLE
Lane Connection tool does not give UI feedback when lane is connected.

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#1485]
When I making a new lane connection, the bezier snaps to lane. When I click there is no visual difference in the bezier. I wouldn't know if connection was successfully made unless if I move the mouse away which is annoying.

![image](https://user-images.githubusercontent.com/26344691/159478755-9d278d57-8a93-49ed-b63f-90d1b5fc6ce7.png)
making a connection does thicken the line a little bit if you know where to look. but as you can see from picture above its too subtle.

Possible solutions:
- don't snap to lanes
- create a dashed line when removing connection
- change mouse cursor to  `+`/`x` when adding/removing connections respectively
- the line thickness could be visibly different.
- differentiate by using filled or hallow lane connection overlay.
- EDIT: differentiate by using white color #670
- EDIT: reduce opacity of the floating lane beizer
- a combination of above

**Comment by aubergine10** [comment]
I think a combination will work best - there's different contexts of situational awareness.

> the line thickness could be visibly different.

Dragged line could be thinner so when a connector is added, the user sees line getting fatter. Likewise, when connector removed, the line would get thinner.

> don't snap to lanes

I'd wait to see whether line thickness tweak works first, as I suspect its effectiveness of that will be dependent on lane snapping.

> differentiate by using filled or hollow lane connection overlay.

Yes! This will be particularly helpful on large/complex junctions with herds of lane connections; it will make it much easier to see at a glance which outgoing lanes are connected to currently selected incoming lane.

> change mouse cursor to +/x when adding/removing connections respectively

Yes, definitely! Although I'd use `-` rather than `x`. To me `x` means 'delete' which seems ambiguous in situations where there's multiple connections to a given lane. Using `-` subtract is a bit more specific and also visually more simple.

Maybe something like this for "add" (and a red `-` for "subtract"): 
![image](https://user-images.githubusercontent.com/1386719/159565192-98da58a9-8493-4a67-92a2-8dc69744a648.png)

Is there some way to extract the pngs of the existing cursors used by the game? That would help with constructing new cursors.

**Comment by kianzarrin** [comment]
@aubergine10 Its going to be hard to have the bezier overlay to be both thin and hollow because if it is thin then there is not much area left inside. we need to consider the borders have some thickness too (maybe I should think out the borders but I am not sure if it is possible).

> Yes! This will be particularly helpful on large/complex junctions with herds of lane connections; it will make it much easier to see at a glance which outgoing lanes are connected to currently selected incoming lane.

how?

**Comment by kianzarrin** [comment]
Is this issue a duplicate of #670

**Comment by kianzarrin** [comment]
Before (https://github.com/CitiesSkylinesMods/TMPE/pull/635#pullrequestreview-355647204)
![before](https://user-images.githubusercontent.com/1386719/74113101-f9b9bc00-4b99-11ea-8f8f-e207b53d90db.png)

Now:
![nottop](https://user-images.githubusercontent.com/26344691/159478755-9d278d57-8a93-49ed-b63f-90d1b5fc6ce7.png)
where did that white sheath go? its no longer on top.
@krzychu124 Is this regression?

**Comment by kianzarrin** [comment]
@aubergine10 I think I will do this:
- make floating line white and hollow so that we can see if there is a connection underneath.
- mouse cursor also shows if we are adding/removing a connection.

**Comment by chameleon-tbn** [comment]
to be consistent we would at least a general TMPE cursor and the + / - one. otherwise it will look strange if suddenly within TMPE the cursorstyle changes... and if we start this various more custom TMPE cursors might be needed.

imho also it would be needed to add generally code for custom cursor to TMPE... or is this already build in somewhere? @aubergine10

**Comment by krzychu124** [comment]
@chameleon-tbn could you prepare few cursor textures to solve the problem? I'll add a bit of code to support it.

**Comment by aubergine10** [comment]
@chameleon-tbn For cursor design I was thinking it would be good to base our cursors of the default game cursor to give users a familiar feel.  (The example image I posted earlier was just grabbed off internet as a vague illustration of how +/- might be added on to the game cursor)

**Comment by kianzarrin** [comment]
test icon 
![image](https://user-images.githubusercontent.com/26344691/160126984-cfb04039-3960-44bd-9135-307ecb2ded06.png)

**Comment by chameleon-tbn** [comment]
@aubergine10 i did with Arrow Pointer, but imho w/o Looks better
![cursor_add_lane_connector_256](https://user-images.githubusercontent.com/37211016/160199653-f487feaf-b2d7-4ec2-87fb-260ab2565473.png)
![cursor_remove_lane_connector_256](https://user-images.githubusercontent.com/37211016/160199657-bea613d2-1a15-4d2a-a6c7-aae69c6b7f90.png)
![cursor_add_lane_connector_-_256](https://user-images.githubusercontent.com/37211016/160199659-eb9a40e2-e2b0-4319-93e2-b030eb293918.png)
![cursor_remove_lane_connector_-_256](https://user-images.githubusercontent.com/37211016/160199660-b5c2f1e2-0029-4c4d-a106-cd8af9b44810.png)
