### ISSUE TITLE
Lane arrow option disabled after building a new road

### ISSUE THREAD

**Issue by deanholden** [CitiesSkylinesMods/TMPE#1756]
### Describe the problem
When connecting roads to create a junction  anywhere on my map the lane options under the "Lane Arrows" option are greyed out. The tooltip says "Arrow direction is not allowed based on the current intersection profile".

### Steps to reproduce

1. Create a new junction by connecting a new road to an existing road
2. Click "Lane Arrows" in TMPE
3. Lane "Arrow drections" options are greyed out are disabled with tooltip message above
4. Save and reload game
5. Lane options return for that particular road
6. Create another new junction by connecting a new road to an existing road
7. Lane options for this road are greyed out are disabled with tooltip message above. Other roads still have the lane options

### Log files

[Player.log](https://github.com/CitiesSkylinesMods/TMPE/files/12416849/Player.log)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/12416850/TMPE.log)

### Savegame?

[Savegame](https://steamcommunity.com/sharedfiles/filedetails/?id=3024461426)

### Screenshots?
<img width="1680" alt="Arrows" src="https://github.com/CitiesSkylinesMods/TMPE/assets/5751004/44825b95-c003-4c51-a99a-a033a679f416">

### Notes or questions?
I have had several mods installed. However I've removed all of them, unsubscribed and resubcribed to TM:PE and still have the same issue.

**Comment by krzychu124** [comment]
Subscribe to [Broken Nodes Detector](https://steamcommunity.com/sharedfiles/filedetails/?id=1777173984) then scan and fix all broken nodes it finds. 
Using a lot of pedestrian and bike paths greatly increases chance to trigger broken node which then breaks update loop (resets internal lane connections, kind of infinitely), so the mod constantly invalidates available lane arrows.

Problem will immediately solve once you fix broken nodes. You don't need to do anything other than scan and fix all broken nodes. Correctly fixed node should not bug again and they usually break because ped/bike path node has been placed slightly to far from the road

**Comment by deanholden** [comment]
Thanks @krzychu124. Your advice was perfect. I found just one broken node with Broken Nodes Detector where a path that wasn't connected properly and as soon as I fixed that, everything else started working again.
