### ISSUE TITLE
Linter & Code Quality

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#216]
stub

This is in reference to #211 

I have some stuff in mind, will add it later.

**Comment by aubergine10** [comment]
These three:

* [**StyleCop**](https://github.com/StyleCop/StyleCop) - focuses mainly on the layout and formatting of your code.
* [**Codemaid**](https://github.com/codecadwallader/codemaid) - focuses on organising your code (like order by member type, removing unused `using` declarations, etc)
* [**Roslynator**](https://github.com/JosefPihrt/Roslynator) - offers lots of code fixes and suggestions, in addition to those native to VS2017.
* Speaking of which, we should also customise the settings of the M$ stuff that's bundled with VS2017. From memory most of the rules are turned off by default. 

From vague memory dymanoid used StyleCop in the [Real Time mod](https://github.com/dymanoid/RealTime) to ensure consistent code comments, etc. This would be particularly useful for the planned TM:PE API (couldn't find issue tracking that) as we could use the proper code comments to auto-generate API docs to github.io, not to mention just making the source far more maintainable to anyone who hasn't been working on it the past 3+ years ;)

There is also a non-open source, but free, [U2U Consult Performance Code Analyzers](https://marketplace.visualstudio.com/items?itemName=vs-publisher-363830.U2UConsultPerformanceCodeAnalyzersforC7) which might be worth investigating. I don't know if it's usable with the version of .Net Framework that C:SL limits us to?

All of the above work on VS2017 and would thus be suitable for open source contributions.

I don't use the JetBrains IDE (Riser?) so can't comment on that. @krzychu124 might have some ideas in that respect.

**Comment by aubergine10** [comment]
@VictorPhilipp We should ideally make a decision (well, really a decision between you and krzychu) on these things prior to any major code refactorings (such as move to harmony)?

**Comment by VictorPhilipp** [comment]
There is also [SonarLint](https://www.sonarlint.org/visualstudio/) which, according to https://stackoverflow.com/questions/748631/lint-for-c-sharp also uses Roslyn under the hood. It can installed directly from the VS marketplace: https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017
We should also consider to implement a build pipeline (e.g. Travis CI) that runs for each pull request and merge. The linter and (later) tests will have to run successfully before a PR can be accepted.

An important aspect is integratability into the IDE and ease of use. I have just downloaded all four tools and try them for a while.

**Comment by VictorPhilipp** [comment]
Links to marketplace:
- Roslynator 2017: https://marketplace.visualstudio.com/items?itemName=josefpihrt.Roslynator2017
- SonarLint: https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017
- CodeMaid: https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaid
- StyleCop: https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop

**Comment by VictorPhilipp** [comment]
@krzychu124 Maybe you could set up Travis CI for this repo? https://travis-ci.org/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition

**Comment by VictorPhilipp** [comment]
I checked **StyleCop**:
- 👍 It works
![grafik](https://user-images.githubusercontent.com/4333935/54077613-21820f00-42bb-11e9-90e4-f8800a7a4a0f.png)

- 👎 You cannot set severity by issue type, only for all issue types in general

- 👎 Build integration does not work. The project is broken after enabling and I had to manually repair the .csproj file. It is missing some StyleCop project
![grafik](https://user-images.githubusercontent.com/4333935/54077626-4ecebd00-42bb-11e9-82a1-4e3c0bad35a1.png)
![grafik](https://user-images.githubusercontent.com/4333935/54077628-58582500-42bb-11e9-8eae-4337f3dd6b22.png)

- 👎 You cannot group findings because StyleCop does not fill the respective fields in the error log (e.g. "Code" and "Tool")
![grafik](https://user-images.githubusercontent.com/4333935/54077655-a9681900-42bb-11e9-9a7d-1c813514cb19.png)

Conclusion: 👎

**Comment by VictorPhilipp** [comment]
I checked SonarLint:

- 👎 Does not support .NET 3.5

**Comment by VictorPhilipp** [comment]
I checked **Roslynator**:
- 👍 Seamless integration in VS
![grafik](https://user-images.githubusercontent.com/4333935/54077833-2ac0ab00-42be-11e9-91d5-342b03bbba15.png)
- 👍  Supports setting the severity for every issue type
![grafik](https://user-images.githubusercontent.com/4333935/54077838-44fa8900-42be-11e9-8da8-ced0a76b6666.png)
- 👎 **Does not work**. No issues are shown in the error list, although I have set every severity to "Error". I followed the setup instructions from https://github.com/JosefPihrt/Roslynator/blob/master/docs/HowToConfigureAnalyzers.md

Maybe the problem is caused by the old csproj format we use (it's from VS 2015)? I tried to update it to the new format (https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) but that did not make any difference.

It's sad. Roslynator looks promising but I am unable to get it running.

**Comment by VictorPhilipp** [comment]
Regarding **CodeMaid**: This tool does not provide any static code analysis rules

**Comment by VictorPhilipp** [comment]
@krzychu124 was magically able to create a build pipeline which executes StyleCop. The VS project file was also fixed.

Next steps:
- Select which rules we want to use
- Fix all Stylecop reports
- Handle detected issues as errors

**Comment by dymanoid** [comment]
Do not use that StyleCop version, it's obsolete.

Use:
[StyleCop.Analyzers](https://www.nuget.org/packages/stylecop.analyzers/)
[FxCop Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)
[Roslynator](https://www.nuget.org/packages/Roslynator/)

They are implemented as Roslyn analyzers and can be easily integrated in any build environment, the severity of each particular issue can be configured (info/warning/error/ignore), etc etc

See the Real Time repo for examples.

**Comment by krzychu124** [comment]
Yeah, I know, that's why we are using StyleCop.Analyzers. Great extension.

Thanks for links to other code analyzers :wink:

**Comment by aubergine10** [comment]
Will we add any more of the analysers listed above or can this issue be closed?

**Comment by aubergine10** [comment]
Some analysers were added to solution around v10.21 so closing this.

Also, @kvakvs added brief style guide to wiki (also linked from contributing guide) here: https://github.com/CitiesSkylinesMods/TMPE/wiki/Code-style-and-naming
