### ISSUE TITLE
Global setting for maximum floating distance when parking

### ISSUE THREAD

**Issue by Sipke82** [CitiesSkylinesMods/TMPE#298]
When cars found a parking spot, it would be nice if we could set how far they are allowed to "float". I used to limit that with the Rush Hour mod, but as that one is now dead and real time is the new standard in that regard. it means that there is no longer a place to set that distance. IMO TMPE would be the correct place for this setting, i guess it makes sense to set this via the global config xml?

**Comment by aubergine10** [comment]
Float?

**Comment by Sipke82** [comment]
Yes, the final part of the movement, they "float" towards their parking spot. Sometimes they "float" for quite some distance before arriving at their parking spot. 

This floating behavior is also clearly visible with the multi level parking garages.

**Comment by FireController1847** [comment]
@aubergine10 I think he's talking about the point at which vehicles will begin the parking process and detach from the road. For example, if you have a multi-level parking lot asset, vehicles will detach from the road and literally float to a higher level. I think the direct movement from the road to the parking space is what he means by "float".

**Comment by FireController1847** [comment]
[Here's a video](https://www.youtube.com/watch?v=Yv_KgpNuoqU) showing what (I think) he's talking about.
![Here's a 15 second gif of the 16 second video](https://media.giphy.com/media/Qw11viSKTWzVmuBg4Z/giphy.gif)

**Comment by Sipke82** [comment]
Yes exactly that! In the old Rush Hour mod, you could define the maximum distance to allow that.

This behavior is especially annoying when you have a parallel road nearby your parking lot road, cars will just float straight through the bushes to a parking spot. instead of driving to the parking lot road first.

**Comment by miguelrs** [comment]
I find this behaviour really annoying 😞  

Note that it doesn't happen only with multi-level parking assets, but with any parking space. I've got a city with a lot of tourism, a lot of pedestrian roads with no parking and no much public transport, and I see literally all the time cars "floating" detached from the road, going through dozens of buildings to park on a road far away... 

If it helps, I noticed this happens *only* with tourists, while local people does drive *perfecty* to the parking space, and if it's used, they drive to the next one, etc... which makes me think it must be fixable...  

In particular, I notice this with tourists that drive to my train station or my harbour, in order to leave my city. They drive up to a point on the road closest to the station/harbour (which I guess they stablish as the destination), and once they reach that point, they start "floating", regardless of whether the parking slot is 1 meter or 1 mile away...  

Anyway, just wanted to share in case it's useful - apart from this issue, the mod is definitely a must-have! Great work!! 👏

**Comment by krzychu124** [comment]
We are aware about floating cars 😕 and that one thing cannot be changed even if we improve `ParkingAI`. Most of the assets, I would say 95% of multi-level parking's doesn't have internal roads system inside so it's impossible for us to force cars to drive into parking building and then guide realistically to selected parking space(could be random, doesn't matter). 
I doubt that's even possible to add functional road inside building, but I'm not familiar with asset creation so I might be wrong. 
We have plans for `ParkingAI` improvements, as you said floating is really annoying, not just to level-parking's but even road parking space, so in the near future I will try to look into it and enhance/fix bug in that area. We need to create some tools (currently in development) for testing pathfinder first to get view where could be the problem and then test the fixes.

**Comment by miguelrs** [comment]
👍 thanks a lot for the effort! 🏆  
Just to emphazise, I looked at my citizens a lot, and I'm pretty sure this only ever happens with tourists - local people do it perfectly fine... I have no idea how the code works, but there must be something in the local citizens' behaviour that differs from the tourists' one, that might be somehow replicated...

**Comment by Sipke82** [comment]
You can place a functional road in a building using an anarchy mod. Therefore I think such a setting should belong in the global xml. So that advanced users can fiddle with it.

**Comment by aubergine10** [comment]
@krzychu124 did merged PR #993 resolve this issue or would an xml setting still be useful?

**Comment by krzychu124** [comment]
Yes it solved the issue, if they still float there must be other pathfinding issue, might be even a game bug (or a sort of a fallback behavior). 
Anyways, there must be something wrong because sometimes vehicle finds a path to parking spot that should be considered as definitely too far from the parking spot but game accepts it. I haven't found the reason of that but it will cause drifting, obviously. Sometimes when game should remove path and despawn vehicle (when valid path cannot be found) it lets the vehicle drift to the target position (might be a bug somewhere in the code, probably requires a very specific scenario).

**Comment by aubergine10** [comment]
Ok, closing this #298 as fixed by #993.

Regarding that other problem, is it worth opening separate issue? (or just reopen this #298 if you want to track it here)
