### ISSUE TITLE
UI: More accurate lane routing arcs

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#3]
The lane routing lines at junctions don't follow the actual path the vehicles take, they just use a very basic arc between source lane and destination lane.

Would it be possible to use the same approach that the vehicle AIs use in order to create more accurate lines to depict the lane routing? They'd still be an arc, but the properties of the arc would be more accurate based on the actual trajectory the vehicles take.

While this in itself is a minor and somewhat superfluous enhancement, it would be very useful for several other enhancements which I'll post as separate tickets.

**Comment by krzychu124** [comment]
Current state of develoment...
* Perfect
<img src="https://user-images.githubusercontent.com/19638970/52886839-ed14aa80-3175-11e9-9673-f88d10ef71cd.png" width="500">

* Perfect
<img src="https://user-images.githubusercontent.com/19638970/52886840-edad4100-3175-11e9-9638-ddaa10079e18.png" width="500">

* Still not the best path and I have no idea how to catch this type of connection yet (diverge - merge)
<img src="https://user-images.githubusercontent.com/19638970/52886841-edad4100-3175-11e9-9a9d-441b8dad2d77.png" width="500">
* Again problem with diverging lanes (pink)
<img src="https://user-images.githubusercontent.com/19638970/52886838-ed14aa80-3175-11e9-821f-b7d27884c80c.png" width="500">

* In addition, sometimes path connecting straight lanes is not calculated correctly
<img src="https://user-images.githubusercontent.com/19638970/52887555-7a58fe80-3178-11e9-868c-90004cfbfc4f.jpg" width="500">


### Bonus
<img src="https://user-images.githubusercontent.com/19638970/52887825-7e395080-3179-11e9-83f3-472560d3c8b4.png" width="500">

**Comment by aubergine10** [comment]
omfg that is huge improvement! 

I note also on the last image the u-turn at the bottom is upside down.

For catching the connection types, I think there's already something in TMPE that does that - specifically the code that works out default lane connections I think - see bottom section of this wiki page in old docs: https://tmpe.viathinksoft.com/wiki/index.php?title=Junction_%26_transition_routing

**Comment by krzychu124** [comment]
> I note also on the last image the u-turn at the bottom is upside down.

I know that was bonus of the bonus 😉 

I am sure you've noticed too that there are no straight lane connections because they are bugged now 😄

Moreover I have to work on performance because last image have been eating few fps per added connection 😕  (currently every connection is calculated on the fly while rendering - no caching) 

I think the best would be create textures/ meshes from connection (on the fly) and cache somewhere to greatly increase performance - similar as path visualizer is doing it and intersections of connection curves would be easier to detect, I think. 
Additionally I think I will need textures for those triangles and squares, but I will try to generate them using code first.

**Comment by aubergine10** [comment]
How are textures done for the arrows that flow along bus route lines done? Remember we'll need to be able to colourise them (eg. yellow for arrows on the source segment) and fill them (for lanes that have at least one incoming connection), etc.

As for path visualiser, I assume that it's already dealing with everything we'd need for the lane connector visualisation? Like, when I route a bus through a junction, the route line is already showing accurately where the bus will go (as far as I can tell). We'd just need thinner line.

**Comment by aubergine10** [comment]
Not sure if it's any use, but there's various node/segment/lane flags that could be inspected, many of which are described here: https://cslmodding.info/asset/network/#flags

**Comment by krzychu124** [comment]
Finally managed to create most accurate lane connections ever! 🤣 🤣

![zrzut ekranu 119](https://user-images.githubusercontent.com/19638970/53363962-053ab580-393e-11e9-80c3-2f1ee50e5a82.png)

**Comment by aubergine10** [comment]
That's freaking awesome!

**Comment by Sipke82** [comment]
Nice work, this got me thinking. Perhaps this is a nice idea:
When you start to work on manually connecting lanes, perhaps it would be nice that per default all the lanes are drawn, so you will only have to remove the ones you don't like. Because in my experience i usually want to keep 80% of the default lane connections...

**Comment by aubergine10** [comment]
Tagging #985, #282, #932
