### ISSUE TITLE
Possible to change lane arrows when highway rules are enabled

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#569]
when you activate highway rules it says you cannot change the lane arrows. But in the following scenarios users can intentionally/unintentionally change the highway lane arrows when the highway rules are enabled:
A) Connecting the lanes using lane connector changes the lane arrows. deleting the connections does not revert the lane arrows.
B) assign the lane arrows on highways, before enabling the highway rules.

I suggest to revert the highway lane arrows back to default when we remove lane connections or when we activate highway rules.

This is potentially related to the delete/clear feature I requested in #568

**Comment by kianzarrin** [comment]
Why do we need to prohibit user to change lane arrows anyway. This also limits the reach of my turning lane separation quick-edit feature. Maybe I should do something similar with the lane connection too.

**Comment by aubergine10** [comment]
I actually have no idea why the limitation is in place when highway rules are active. That was implemented while I was taking a break from the game some years back.

I feel that as standard we should always endeavour to allow global settings to be overridden at the node/segment/lane level (applicable). The only exceptions to that would be a) if it made code a nightmare to maintain, b) causes performance issues or c) causes usability issues.

So, unless someone has reasons otherwise, I'd love it if we could customise lane routing (via arrows or connectors, etc) when highway rules are active. At the very least we should fix the bugs you identified.

@kvakvs You did a load of work on the lane connector stuff, any feedback?

**Comment by kvakvs** [comment]
I'd say allow.
But when highway rules active, and the user opens lane arrows or lane connectors, we show some visual icon on that junction.

**Comment by brunoais** [comment]
> we show some visual icon on that junction. The natural question user will have, what that means, we need to solve somehow, maybe a mouse tooltip.

I'd go with the tooltip option

**Comment by kianzarrin** [comment]
now that the highway rules is a legacy feature (replaced by highway merging rules) I set this to low priority. maybe we should close this? there is no point improving legacy feature.
