### ISSUE TITLE
Lane arrow super-small on some resolutions

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#571]
Biffa reports super-small UI on the lane arrows popup:

![image](https://user-images.githubusercontent.com/1386719/69596287-08142500-0ffa-11ea-810a-bc3528399d02.png)

That's on STABLE release, but I assume similar on LABS and ALPHA.

I've not seen this before; it might be something to do with screen resolution or gfx drivers?

As we already plan major overhaul of lane arrow UI (see #391) I suggest we do that rather than spend time on the old UI...?

@kvakvs What is the current plans for #391?

**Comment by kvakvs** [comment]
I've see that. Biffa started streaming in 4k, and that UI window is pixel-sized not scaled to the screen %.
I already have a working prototype of GUI.
The creation API makes me "poop in feer" i need to focus once again and make the API pretty, and then we can begin replacing game windows one by one with the new UI, which is capable of being scaled to screen % or parent %.
The lane arrow overhaul has no GUI at all (it should because the user will have no idea what each mode means).
