### ISSUE TITLE
Request: Vehicles choose random lane on roads if possible

### ISSUE THREAD

**Issue by Monniasza** [CitiesSkylinesMods/TMPE#590]
### Describe your idea

Vehicles would use random lane on a road, switching only when necessary

### Screenshots?
None

### Notes or questions?

Example: 

Original toll booth vehicle counts:

Original                       Improved
16/00/00/00                04/04/04/04

**Comment by kvakvs** [comment]
How is this different from Dynamic Lane Selection?
https://tmpe.viathinksoft.com/wiki/index.php?title=Dynamic_Lane_Selection

**Comment by kianzarrin** [comment]
Isn't it better if we have individual driving styles for drivers?

**Comment by aubergine10** [comment]
Dynamic Lane Selection already has individual driver styles, specifically:

* Each driver gets their own 'pseudo-random seed'
* That seed determines, for that driver:
    * A speed nerf/buff of their vehicle speed
    * When they will make lane change decisions
* The DLS slider in mod options determines how many drivers will be affected (higher DLS means more drivers but at the expense of frame rate due to increased processing load).

**Comment by Monniasza** [comment]
It would keep single lane for as long as possible.

**Comment by aubergine10** [comment]
The lane lookahead gets computationally expensive and it would likely be non-viable to try and route it through junctions in realtime: https://tmpe.viathinksoft.com/wiki/index.php?title=Dynamic_Lane_Selection
