### ISSUE TITLE
Path Finding Issue ( all the time close to 262144 ) and constantly broken node with train and metro.

### ISSUE THREAD

**Issue by Raptorheart** [CitiesSkylinesMods/TMPE#613]
Dear all, 

I am encoutered huge problem with my below average city, with 283K pop. The Path finding is oscillated between max level and 240000 approx. Because of this ( or not ) I have all the time problem with train and metro than I have all the time to redraw/rebuild the line for don't let them stuck in place, sometimes 'couldn't find path appears' between two metro station and I have to destroy and rebuild some part of the line for fix the problem. This is not happening one or two times, but all the times ...

Of course If I enable dispaws path finfing value became better but with this I encountered issue with good deliverie for the commercial sector, as some deleverie truck will dissapears even without trafic jam. 

Trafic is really busy but I don't have huge trafic jams, average traffic flow is something 80%, so this is not so bad, because I made a huge metro network. Average trafic is essentially truck for goods deliveries and industries.

If i reset trafic path finding became only 115819 when I have only 2718 active cars ...
If I remoce citizen agent throw the load screen mods and it's becoming far better ( something like 80000 ) so there's something wrong here.

For be honest I think the problem can coming from Five thing :
-TMPE Labs
-Mor vehicule Mod
-A bug somewhere where cims became stucks or something like that, increasing path number, I search but I found nothing.
-A bad metro design than create to mutch more path finding request, but I don't think this last is the problem, to be honest.
-Just the limit due to citizen number ? I see some guys who build 1million citizen city on youtube, so how ?

I try to remove every mods and the problem is still here:
 :-(

You can find my savegame here :
https://steamcommunity.com/sharedfiles/filedetails/?id=1969639989

Screen Shot of show limits in city games after and before reset trafic :

![20200115_045520](https://user-images.githubusercontent.com/59924510/72445484-0cff8480-37b2-11ea-81ed-66b996d8e768.jpg)
![20200115_044933](https://user-images.githubusercontent.com/59924510/72445470-0a9d2a80-37b2-11ea-935d-286f2882b1e0.jpg)

Txt files with list of mod/asset/output.log, etc :

[Files.zip](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4065568/Files.zip)

With some times after the save games I share, **all the commercial sector from all type**, from the newest to the oldest will start to crying " not enought goods" & "not enought customer" or the two, and the city will start to slowy collapsing :('...

**Comment by krzychu124** [comment]
I will check your savegame later but let me tell you what could be the other cause of max path units.
Every pathUnit can contain up to 12 different path.positions (waypoints) and pointer to the next pathUnit instance.  Theoretically there is no limit of pathUnits per chain because you when you(pathfinder) needs to add next positions it will create new PathUnit and set nextPathUnit pointer to it on previous PathUnit. Pathfinding has to calculate path (usually chain of pathUnits) for each active instance.
Let's consider following numbers, I would say pretty low but they should give you some image:
- assume ~3 pathUnits per citizen and ~5 pathUnits per vehicle: 
  - for vanilla limits it will be 3 * 64k + 5 * 16k = 272k (usually it's less than 3 per citizen),
- calculate approximate pathunit usage (e.g. from last screenshot):
  - 3 * 34k + 5 * 2.7k = 115.5k (look you have 115k there - pretty close to actual value)
- now let's take the first screenshot: 
  - 3 * 57k + 5 * 24k = 291k (~30k more that the limit)
Numbers can vary depends on how your city is built, but that simple example should immediately point the problem.
I forgot to mention about how positions are set in pathUnit. Assume that instance (e.g citizen) has to move only through 3 junctions to get to the destination. Here you have possible pathUnit positions:
Let's say that junctions are connected with 3 segments each
- start segment
- segment 1,
- segment 2,
- segment 3,
here you have first junction
- segment 1,
- segment 1,

**Comment by krzychu124** [comment]
I will check your savegame later, but let me tell you what could be the other cause of max path units.
Every `pathUnit` can contain up to 12 different `path.positions` (waypoints) and pointer to the next `pathUnit`.  Theoretically there is no limit of `pathUnits` per chain because you when you(pathfinder) needs to add next positions it will create new `pathUnit` and set `nextPathUnit` pointer on previous `pathUnit`. Pathfinding has to calculate path (usually chain of `pathUnits`) for each active instance.
Let's consider following numbers, I would say they are pretty low but they should give you some image how it works:
- assumming ~3 `pathUnits` per citizen and ~5 `pathUnits` per vehicle: 
  - for vanilla limits it will be 3 * 64k + 5 * 16k = 272k (usually it's less than 3 per citizen),
- approximate `pathUnit` usage from last screenshot:
  - 3 * 34k + 5 * 2.7k = 115.5k (look you have 115k there - pretty close to actual value)
- now let's take the first screenshot: 
  - 3 * 57k + 5 * 24k = 291k (~30k more that the limit)

Numbers may vary, depends on how your city is built, but that simple example should immediately point the problem.
Here is simple example how positions are set in `pathUnit`. Assume that instance (e.g citizen) has to move only through 3 junctions to get to the destination. Here you have possible `pathUnit` positions:
Let's say that junctions are connected with 3 segments each
- start segment
- segment 1,
- segment 2,
- segment 3,
here you have first junction
- segment 4,
- segment 5,
- segment 6,
second junction
- segment 7,
- segment 8,
- segment 9,
third junction
We've used 10 positions to get from point `A` to point `B` which distance were only three junctions (9 segments). Now imagine vehicle (each lane change on the same segment is additional position used in `pathUnit`) that has to drive to the outside connection through roughly 100 segments

**Comment by Raptorheart** [comment]
Thanks you dude for your fast answers !

So, this is because i am close or at the the limit, path is udge because of the "udge" number of citizen/cars. Optimize is the only solution, or try to made thing work with dispawn. I will know it for the next city I made.

Do you know if there's something like 'more path limit' ... made a city with office only is kinda boring  if we want to made them big :( ...

**Comment by krzychu124** [comment]
I think no one create it yet (maybe it's too hard or time consuming). I believe that's way harder than increasing a vehicle limit

**Comment by Raptorheart** [comment]
> 
> 
> I think no one create it yet (maybe it's too hard or time consuming). I believe that's way harder than increasing a vehicle limit

I will just add "industrie rebalance" mod, I will gain some path with less truck, it will help the city work with consuming less path, and may be made me able to finish it.
Thanks you for your support and for your impressive work over this mod, I really appreciate it !

**Comment by aubergine10** [comment]
There's a few other ways to reduce number of vehicles listed in performance tuning guide (see **Traffic Reduction Mods** section): https://steamcommunity.com/sharedfiles/filedetails/?id=465790009

**Comment by Raptorheart** [comment]
> 
> 
> There's a few other ways to reduce number of vehicles listed in performance tuning guide (see **Traffic Reduction Mods** section): https://steamcommunity.com/sharedfiles/filedetails/?id=465790009

Thanks you for the advice, I will add ouside connection and no seagull, it will help to !

**Comment by krzychu124** [comment]
Use https://steamcommunity.com/sharedfiles/filedetails/?id=2710657019 (More PathUnits) if problem persist. Closing
