### ISSUE TITLE
A bug with cars staying in one lane on highways.

### ISSUE THREAD

**Issue by alexic123** [CitiesSkylinesMods/TMPE#674]
### Describe the problem
I saw that the cars on the highway, are using only 1 lane and when they are close to a junction, although the exit is 1 lane and after it it's a 3 lane highway or 2, they are still gonna change the lanes and go to the first lane.. Dunno why. I switched back to tmpe 10 and I had the same problem, soo I switched again back to 11, and I still have the problem. I dont know if it's from the game or from the mod.

### Log files
https://uploadfiles.io/z6s7sfof

TMPE log: https://uploadfiles.io/5ezv4sph

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=1992957107

### Screenshots?
https://steamcommunity.com/sharedfiles/filedetails/?id=1992984631
https://steamcommunity.com/sharedfiles/filedetails/?id=1992984691
https://steamcommunity.com/sharedfiles/filedetails/?id=1992984801
https://steamcommunity.com/sharedfiles/filedetails/?id=1992984763 

### Notes or questions?
Again, they are using only 1 lane on the highway and if there is a 3 lane highway and somehow they spread to all 3 lanes, when they approach a exit lane, they use only one lane to go straight, one to exit and the middle lane is clear...

**Comment by krzychu124** [comment]
First, I loaded your savegame but I can't find that intersection with tunnel you posted on screenshot
Another issue might be this thing:
![image](https://user-images.githubusercontent.com/19638970/74111078-0c2ff780-4b92-11ea-904c-bb4b12920204.png)
You located industry in one place but incoming and outgoing lanes have no enough throughput to properly service that area. You also have 'Disable despawning` option turned on which even worsen that situation. Everything clogs up because not enough road network throughput and vehicles have to choose lane way earlier so you see them on one lane (there is no other available enter to that area)

**Comment by alexic123** [comment]
Yeah, I know, but this is not the problem. This will go up and down, like now it's full, after a min it's empty, but that intersection, from here, go up, and a but on the right, it's outside or my city, I bought, that square only to modify that intersection, cuz I've had a lot of cars on the highway..

**Comment by alexic123** [comment]
I was also thinking, of deleting all mods and assets and then start a new map and go with vanilla and then use some mods.. I think my game is a bit bugged cuz, I dont get demand for anything and I have some assets that done even load..

**Comment by krzychu124** [comment]
More info about [DLS ](https://tmpe.viathinksoft.com/wiki/index.php?title=Dynamic_Lane_Selection). It will stop working if traffic is piling up. If you use Highway rules(outer right is the best lane to exit - that's why they take it), you should also use either lane mathematics at junctions or lane connector to manually create lane routings.
If issue persist let us know (there was game update in the mean time)
