### ISSUE TITLE
Add lane highlight to Parking Restrictions tool

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#702]
While not immediately obvious, a lane highlight still useful for this tool as it has an "apply to route" mode (`Shift+Click`) so good to highlight the affected route!

This is already done, by accident lol (see https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/682#issuecomment-586504886)... just creating issue to track it separtely and ensure it appears in the change notes.

![route mode](https://user-images.githubusercontent.com/26344691/74574222-9cec4600-4f8b-11ea-9454-76a38b9659ac.jpg)

**Comment by aubergine10** [comment]
@kianzarrin This would be a good time to check what's happening with #516 - seems one way roads, even if they have two parking lanes, only get one parking icon. As user I have no idea if it affects both lanes or just one, and ideally want separte control over each lane.

Also tagging #667

**Comment by kianzarrin** [comment]
For the sake of thoroughness I tested roads with different prefab that do not produce junctions (because they have matching lanes):
![Cities_HEd0GhUtH8](https://user-images.githubusercontent.com/26344691/74576848-60bde300-4f95-11ea-8381-44303145e6cb.jpg)
![Cities_UQePnu9PXn](https://user-images.githubusercontent.com/26344691/74576850-61567980-4f95-11ea-9182-75d808f06f73.jpg)
I tested and confirmed that the overlay accurately shows what parking signs will be affected.

**Comment by kianzarrin** [comment]
![Cities_Y0Nr5XRofe](https://user-images.githubusercontent.com/26344691/74577404-919f1780-4f97-11ea-9284-54677eb39bd0.jpg)
![Screenshot (491)](https://user-images.githubusercontent.com/26344691/74577415-a380ba80-4f97-11ea-92b3-64c38a362747.png)
The latter screenshot is not right

**Comment by aubergine10** [comment]
Ref #33
