### ISSUE TITLE
Mod confict report when both TMPE and other mods use harmony to patch the same method

### ISSUE THREAD

**Issue by pcfantasy** [CitiesSkylinesMods/TMPE#747]
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4259406/TMPE.log)
[output_log(6).txt](https://github.com/CitiesSkylinesMods/TMPE/files/4259407/output_log.6.txt)

@krzychu124 @aubergine10 

I update CSUR toolbox, some users sometime will report mod conflict.

Both CSUR toolbox and TMPE use harmony to patch  RoadBaseAI.UpdateLanes now. This confict should not happen, I do not know why.

https://github.com/citiesskylines-csur/CSURToolBox/blob/master/Patch/RoadBaseAIUpdateLanesPatch.cs

#611

**Comment by aubergine10** [comment]
```diff
Info 805.2317943: ThreadingExtension.OnBeforeSimulationFrame: First frame detected. Detours checked. Result: 1 missing detours
- Error 805.2326772: Traffic Manager: President Edition detected an incompatibility with another mod! You can continue playing but it's NOT recommended. Traffic Manager will not work as expected. See TMPE.log for technical details.
   at CSUtil.Commons.Log.LogToFile(System.String log, LogLevel level)
   at CSUtil.Commons.Log.Error(System.String s)
   at TrafficManager.ThreadingExtension.OnBeforeSimulationFrame()
   at ThreadingWrapper.OnBeforeSimulationFrame()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()

Info 805.2739730: The following methods were overriden by another mod:
- 	<Harmony> RoadBaseAI.UpdateLanes with 3 parameters (RoadBaseAI, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
```

**Comment by krzychu124** [comment]
OK, I think I figured out what is wrong.
Indeed you are patching the same method as we do but using completely different (probably custom) `Harmony` build. It looks like preview release of `Harmony 2.0` but versioned `1.9.9.9`. 

To make patching compatible @CitiesSkylinesMods/tmpe  would have to migrate to `Harmony 2.0.0.X`. 

I think there are no other options from your side, because you are patching methods of struct instances. That feature is not supported by `Harmony 1.2.0.1` so downgrade is not really possible. We don't have data which mods are using `TM:PE`.

Another issue is that `Harmony v2.0` wasn't released yet and selecting intermediate (beta) version might cause even more problems. 
Latest info and full story from the author of Harmony lib can be found [here](https://www.reddit.com/r/RimWorld/comments/fbnm45/harmony_the_full_story/)

**Comment by pcfantasy** [comment]
@krzychu124 

harmony2.0 is not compatiable with harmony1.2, so if TMPE is using Harmony 2.0.0.X, I do not think TMPE can compatiable with other mod which is using harmony1.2

In fact, In order to compatiable with mod which is using harmony1.2, I modified Harmony 2.0.0.X, remove some new features and rename it as harmony 1.9.9.9


https://github.com/pardeike/Harmony/issues/250

**Comment by pcfantasy** [comment]
@krzychu124 

Let`s make this clear. Do you mean to make TMPE and CSUR toolbox compatiable, we should both use harmony2.0.0.X or both use harmony1.2.0.1 ?

**Comment by krzychu124** [comment]
> Let`s make this clear. Do you mean to make TMPE and CSUR toolbox compatible, we should both use harmony2.0.0.X or both use harmony1.2.0.1 ?

@pcfantasy Exactly, we currently use Harmony 1.2.0.1 and as I said earlier, your CSUR Toolbox can't use harmony 1.2.0.1 because some of your patches will fail to apply. I pulled your repo to test if backward migration is possible and nope, I couldn't patch some of methods you use.
Anyways, we are considering migration to latest harmony release in near future.
Latest version [2.0.0.8](https://www.nuget.org/packages/Lib.Harmony/2.0.0.8) was released on nuget 3 days ago and according to Harmony author reddit post linked above is considered as stable.

**Comment by pcfantasy** [comment]
@krzychu124 

Thanks, I understand this now. I have a workaround to patch another place until TMPE move to new harmony.

BTW, it is not easy to move TMPE to harmony.

 As I said, I tried before. But harmony2.0 do not compatiable with harmony1.2. So if some mods still use harmony1.2, there will be a conflict.

So what do you think about this, or if TMPE want to update to harmony2.0, please notify all other modders.

**Comment by krzychu124** [comment]
Yes, we are aware that both versions are incompatible. The easiest way for us would be to update both v11 versions at a time. We will try to notify other modders before we release updated version.

**Comment by aubergine10** [comment]
The move to Harmony 2 is going to happen sooner or later anyway, as we already see with CSUR Toolbox, Network Skins 2, etc.... there is a need for the features of Harmony 2. If necessary we could work with other modders to help them migrate to Harmony 2.

A lot of the much older mods are still using the old detours library by cope. Maybe there is some way we could determine which mods are using Harmony, and if so which version of Harmony they are using? Possibly a small mod that could be subscribed which would log details to game log?

**Comment by pcfantasy** [comment]
@krzychu124  @aubergine10 

Agree, notify me if any plan about harmony2.0, thanks.

**Comment by pcfantasy** [comment]
@krzychu124 

Sorry to ask one more technical detail.  This conflict(two harmony version patch one place) do not affect function, I mean both postfix will still work, right?

Some of my mods use different harmony to patch the same method, use prefix, which seems work fine. 

But in this case, some users report that my postfix is not work after TMPE show mod conflict warning.

Do you have any idea about this?

**Comment by aubergine10** [comment]
FYI: Seems there are lots of versions of Harmony floating around - I've got about 120 mods active, and these are the versions of Harmony assemblies in the app domain:

![image](https://user-images.githubusercontent.com/1386719/75838930-45d5d600-5dbf-11ea-86c3-5b3a4ff9aa1b.png)

**Comment by dymanoid** [comment]
Note: although all the assemblies are loaded into the app domain, only one of them will be used by *all* mods. But which one - that's impossible to predict. It depends on the assembly loading order which is mainly affected by the mod loading order which is, in turn, non-deterministic in Cities: Skylines.

**Comment by pcfantasy** [comment]
@dymanoid 

Do you mean if one mod A use harmony1.2, another mod B use harmony1.3(local build and hacked for some new functions). But in fact, both mods may all use harmony1.2 to patch method. 

So in the case, B mod want to use local hacked harmony1.3 for new functions but the new functions may not work as experted, because in fact B mod is still using harmony1.2.

Is my understanding right?

**Comment by aubergine10** [comment]
There is no way for a mod to say _which_ version of harmony it wants; if there are multiple harmony assemblies loaded (different versions), only one harmony assembly version will be used _by all mods_.

It's exact same problem that RimWorld modders had; whichever version of harmony loads first is used by _all_ mods, regardless of what versions of harmony those other mods bundled.

**Comment by pcfantasy** [comment]
@aubergine10 

Not exactly? You see that NS2 and CSUR toolbox all want new harmony function to patch struct instance. The two mod use local builded harmony version.

Until now, both mod works fine in steam, if NS2 and CSUR toolbox`s patch is forced by other mod`s harmony1.2. Their patches should not apply to struct instance, and will cause function issue.

**Comment by aubergine10** [comment]
Maybe @pardeike could confirm one way or the other?

**Comment by pardeike** [comment]
Maybe a bit long but it sums up what RimWorld went through:
https://www.reddit.com/r/RimWorld/comments/fbnm45/harmony_the_full_story/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by dymanoid** [comment]
@pcfantasy 
Two questions. 

*Are you sure the mods are working as expected?* Maybe they are just lacking some internal functionality due to missing patches but the players just never notice that. If the mod doesn't crash and the main functionality is okay, no player will dig into the details. There are indeed some players having the custom built Harmony instance as the "main" one, and the other mods happen to not use incompatible API, so it just works for those players.

*How can you guarantee that your build of Harmony is used when multiple Harmony-using mods are loaded?* Did you try to compare the Module GUID of the loaded Harmony assembly with the one of your custom build?

**Comment by pardeike** [comment]
There is a method that returns the harmony version: https://harmony.pardeike.net/api/HarmonyLib.Harmony.html#HarmonyLib_Harmony_VersionInfo_System_Version__

**Comment by aubergine10** [comment]
v1.2.0 of DuplicateAssemblyScanner is now in PR review - useful tool if you want to get an idea of which C:SL mods are using Harmony and which of the assemblies are loaded in to app domain, etc: https://github.com/CitiesSkylinesMods/DuplicateAssemblyScanner/pull/16

Note that a mod doesn't even need to be enabled for it's `0Harmony.dll` to get loaded by C:SL.
