### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by michaelkcorti** [CitiesSkylinesMods/TMPE#792]
### Describe the problem
Endless loop of the following message: Object reference not set to an instance of an object [System.NullReferenceException]

Steam Current 1.13.0-f7
Steam Previous 1.12.0-f5
Error message on TM:PE 10.20 about incompatibility.
Deleted TM:PE 10.20
DownloadedTM:PE 11.2.0 Stable

### Steps to reproduce
1. Game opens in Pause.
2. At Play; Error Message: Object reference not set to an instance of an object [System.NullReferenceException]
3. Closing window is of no affect.  Endless Loop of Error Window.  Ending Cities.exe in Task Manager is the only EXIT option.

### Log files
Initialize engine version: 5.6.7f1 (e80cc3114ac1)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
    Vendor:   NVIDIA
    VRAM:     8079 MB
    Driver:   26.21.14.3200

NOTE: LOG FILE IS 914,014 CHARACTERS WHICH EXCEEDS THE MAXIMUM.

[TropicalParadiseLogFile.docx](https://github.com/CitiesSkylinesMods/TMPE/files/4395445/TropicalParadiseLogFile.docx)

### Savegame?
https://steamcommunity.com/sharedfiles/filedetails/?id=2037498467

**Comment by zaratropia** [comment]
Same here.

**Comment by krzychu124** [comment]
Hi, thanks for the log. Issue is known and caused by old incompatible transport station assets.
Wait for game fix or asset update. You can try unsubscribing old public transport stations but that might cause another set of errors.

```cs
Simulation error: Object reference not set to an instance of an object
at TransportStationAI.IsIntercity () <0x0019f>
at TransportStationAI.AdjustMaintenanceCost (uint16,Building&,int) <0x00030>
at PlayerBuildingAI.SimulationStepActive (uint16,Building&,Building/Frame&) <0x001aa>
at CommonBuildingAI.SimulationStep (uint16,Building&,Building/Frame&) <0x00e6d>
```
@zaratropia if you see different variant of `Simulation error: Object reference not set to an instance of an object` please create another issue and attach log file. If you see exact same error there is no other option than wait for patch/asset update. 

This error is not caused by **TM:PE**. We can't do anything to help you.

@aubergine10  could you update our troubleshooting section in wiki if you haven't done that yet? 
I've seen confirmation it is a little bug in SH update which triggers not 100% compatible assets to throw an error.

**Comment by michaelkcorti** [comment]
Thank you for letting me know.
Appreciate it.

**Comment by aubergine10** [comment]
I'll update troubleshooting wiki.  👍

**Comment by krzychu124** [comment]
@michaelkcorti Here is the fix https://steamcommunity.com/sharedfiles/filedetails/?id=2037862156

**Comment by michaelkcorti** [comment]
Really appreciate you following up.
The fix has worked perfectly.
https://steamcommunity.com/sharedfiles/filedetails/?id=2037862156
Thanks
