### ISSUE TITLE
Automatically lower speed limits on roundabouts [Suggestion]

### ISSUE THREAD

**Issue by scottmcm** [CitiesSkylinesMods/TMPE#793]
Many people use highways for roundabouts, as there's no other 3-lane one-way road in vanilla, or use 80km/h highway ramps for small residential roundabouts as the only 1-lane road in vanilla.

But the roundabout going faster than the connecting roads is both unrealistic and less efficient -- having the speed limit lower makes it easier for traffic to merge onto the roundabout (less time accelerating means they can fit into a smaller gap, and the same distance of gap becomes a longer-in-time gap) and allows for more traffic to be on the circulating roadway at a time.

So it would be nice to have an option for the roundabout auto-setup to also set an appropriate speed limit based on the size of the roundabout.

How fast should it be?  Well, the [FHWA's roundabout technical summary](https://safety.fhwa.dot.gov/intersection/innovative/roundabouts/fhwasa10006/#s1) suggests speeds of 25-50km/h, for different sized roundabouts, and we [know](https://en.wikipedia.org/wiki/Centripetal_force#Formula) that a=v²/r, so it seems plausible for the speed to be linear in the _square root_ of the radius.

Playing with the numbers a bit, setting the speed limit to 4√r (with r in meters and speed limit in km/h) seems plausible

radius (u=8m) | speed limit (km/h)
---------- | --------------------
3 | 20
5 | 25
7 | 30
10 | 36
14 | 42
20 | 50 

So here's a concrete suggestion for how this could work, as a probably-close-enough approximation:
- Estimate the radius of the roundabout as average distance of the nodes from the centre of mass of the nodes
- Toss it in the formula above to get a speed limit
- Just in case, clamp it above 13 km/h [aka 8mph] so at worst the round-to-5mph signs will show 10mph and the round-to-10km/h signs will show 10km/h.  (But the roundabout would need r<1.3u for that to matter, so it shouldn't ever come up really.)
- Don't set any segment above its natural speed limit.  (Just in case the roundabout is _huge_ -- the normal two-lane road shouldn't be a 100km/h roundabout just because someone's making a ring city and it has a 80u radius.  It would also protect [intentionally-slow](https://steamcommunity.com/sharedfiles/filedetails/?id=1391209732) streets.)

Other estimates for the radius could be 1/2π of the length of the roundabout, or anything else that's easy for you get and about-right for anything that's about-circular.  (If the speed limits are a bit off for a "wonky-about" I wouldn't really care.)

**Comment by aubergine10** [comment]
@kianzarrin is this something that could be added to the bulk update tool for roundabouts?

**Comment by kianzarrin** [comment]
My pedestrian bridge build mod can detect the center of the roundabout but I don't think we need it here. I think measure of curvature suffices:
```
segment speed = constant * Vector2.Dot(startDir,EndDir) // maybe cos would work better.
```

**Comment by kianzarrin** [comment]
in any case we should ban parking

**Comment by kianzarrin** [comment]
I think there is a superstition that changing roundabout speed improves traffic! 

I have done some testing of my own and I noticed decrees in traffic flow. It is indeed easier to enter roundabout if approaching car is moving slowly but on the downside approaching cars take their sweet time to leave the roundabout so cars entering the roundabout will have to wait longer for the roundabout to be cleared. You give some, you loose some but on the whole its worst.

Biffa says reducing speed limit on roundabout boosts traffic. While he does plays with roundabout speed limits, he has never checked back (that I know of) to verify if there has been any benefit.

I still think its a good feature because you want to go slowly on roundabouts to reduce accidents ... although this game does not simulate accidents. not to mention the centrifuge force.

I am worried that if we implement this feature, people will think its boosts traffic in CS so I think we should explain in a wiki page that it does not.

**Comment by aubergine10** [comment]
I've seen lots of users building roundabouts out of highway roads, and then proclaiming that their roundabout solved traffic issues.

What is described in OP is essentially "make roundabout traffic speed more realisstic". Personally I spend ages tweaking lane speeds in roundabouts which is a bit of a PITA especially as I can't get much benefit from `Shift + click` in that context.

Maybe we can add a `Realistic speed limits` checkbox to the existing roundabout policies: It would essentially do some math to set the lane speeds for segments in the rounadabout and, ideally, also the segments entering the roundabout.

That way users can choose to have more realistic speeds in their roundabouts, or not. Hopefully calling it `realistic speed` will avoid assumptions that it somehow improves traffic throughput.

Some potentially related issues: #757 , #668

**Comment by kianzarrin** [comment]
we can calculate the `raduis` of the segment like this:
``` c#
dot = startDir . EndDir
angle = acos(-dot)
L = |startPos - endPos|
R = L / ( 2*sin(angle/2) )
```
Now the question is what formula to use to drive speed limit based on the values above.

**Comment by scottmcm** [comment]
If you want to save some trig, I think you [can](https://www.wolframalpha.com/input/?i=simplify+2*sin%28acos%28x%29%2F2%29) do `R = L / sqrt(2 - 2*dot)`.

**Comment by kianzarrin** [comment]
> R = L / sqrt(2 - 2*dot).

Wow I like that so cool! forgot what was sin(x/2) ... should have searched it!

**Comment by kianzarrin** [comment]
@scottmcm what is `√` sign in `4√r`

**Comment by kianzarrin** [comment]
My calculations shows that it should be `11.3*sqrt(r)`

**Comment by kianzarrin** [comment]
> Playing with the numbers a bit, setting the speed limit to 4√r (with r in meters and speed limit in km/h) seems plausible
radius (u) | speed limit (km/h)
---------- | --------------------
3 | 20
5 | 25

How did you manage to create roads so small?! @scottmcm The smallest I could create is radius=8m
![Screenshot (897)](https://user-images.githubusercontent.com/26344691/79977125-66a8d680-84a6-11ea-90ac-aee1a9978886.png)

**Comment by scottmcm** [comment]
@kianzarrin Oh, by `(u)` I meant the 8m road-snapping **u**nits.  So `3u` -> `24m` -> `19.6km/h`. 

And [√ is square root](https://www.fileformat.info/info/unicode/char/221a/index.htm).

I'm glad you like the trig trick!  I tried to figure it out by hand but decided that was too complicated and decided to just ask wolfram alpha in hopes that something existed 😅

Also, I was looking at your original formula again and came up with another way of getting the same thing (thinking in terms of `2R=L/sin(θ)`), with apologies for the mspaint art:
![image](https://user-images.githubusercontent.com/18526288/80048433-06755d00-84c5-11ea-95ea-11f0667c6e5c.png)
Using [Thale's Theorem](https://en.wikipedia.org/wiki/Thales%27s_theorem) (and some poorly justified math that the blue corner has to go from 0° when the directions are parallel to 90° when they're in opposition).

**Comment by aubergine10** [comment]
I assume this could be applied to any bend? So we can make traffic slow down on any curved segment, based on curvature of the segment - regardless of whether it's roundabout or just winding road through the mountains?

Are there any guidelines of traffic speed based on incline/decline of the road? Because if we could mix those two together, optimised enogh for per-frame vehicle AIs, we could get some really awesome and realistic vehicle speeds! (User would set thier desired speed but TMPE would then buff/nerf it depending on various factors).

**Comment by scottmcm** [comment]
@aubergine10 I can't find the table I'm thinking about, but I did manage to find this:
https://www.virginiadot.org/business/resources/LocDes/RDM/Appendix_a1.pdf
![image](https://user-images.githubusercontent.com/18526288/80055075-a3d88d00-84d5-11ea-9e0b-982d9086b739.png)

If I turn that into a formula,
![image](https://user-images.githubusercontent.com/18526288/80055441-7f30e500-84d6-11ea-8b7e-126b343f5e01.png)

And if I turn that into metric <https://frinklang.org/fsp/frink.fsp?fromVal=1.3449+miles+%2F+hour+%2F+%28sqrt%5Bfeet%5D%29&toVal=km%2Fhour+%2F+%28sqrt%5Bm%5D%29#calc>, I think that's
Speed (in km/h) = 3.9204 km/hour/√m * √(radius in m) + 20 km/h

Which is surprisingly close to what I'd guessed for roundabouts, actually, just plus 20.  (But this is a _maximum_ speed, not a _suggested_ speed, so being higher makes sense.)

**Comment by scottmcm** [comment]
@aubergine10 Oh, I forgot to respond to "traffic speed based on incline/decline of the road".  The CSL horizontal compression means that the real-life guidelines will be quite unusable.  A fairly-gentle slope in the game is 1/8 (one default page up per 12 grid units), but that's a 12.5% grade, which is real life is quite severe.  From the same PDF I linked in the previous post:
![image](https://user-images.githubusercontent.com/18526288/80060388-477c6a00-84e3-11ea-9943-1228c7d85b1c.png)
Applying those would force us to slow even well-designed system interchanges to a crawl.

**Comment by aubergine10** [comment]
> Applying those would force us to slow even well-designed system interchanges to a crawl.

Could we approach it as a ratio or something like that?

So we'd say 12.5% grade (game) is equivalent to 3% grade (RL) and adjust speeds accordingly?

The main thing I'm thinking is it would be nice to have traffic that's going up-hill be a bit slower than traffic going down the same hill.

**Comment by kianzarrin** [comment]
> @scottmcm EDIT: Oh, actually, if you have the three points of the quadratic bezier when doing this, this answer claims to have a closed formula for curvature, which is inverse radius: https://math.stackexchange.com/a/2971112

You have some cool math there. I don't have access to segment bezier so going that root is going to be slow. How did you calculated the `angle/2` in your diagram?

And what is grade?

**Comment by scottmcm** [comment]
@kianzarrin Ah, yeah, if you don't have all the bezier points then that's not a fruitful direction.

I haven't yet managed to geometrically prove that blue corner is the same `angle/2` as in your formula.  I just have the informal demonstration that when the angle between the directions is 0°, that blue corner is 0°, when the angle between the directions is 90° that blue corner is 45°, and when the angle between the directions is 180° that blue corner is 90°.

[Grade](https://en.wikipedia.org/wiki/Grade_(slope)#Nomenclature) is just a word for slope with a grade of zero being horizontal.  When reported as a percentage its value is the tangent of the angle (12.5% = tan(7.125°)).

**Comment by Sipke82** [comment]
I was under the illusion that the cars travel slower in bends?..do they really go full speed in tight corners?

**Comment by aubergine10** [comment]
@Sipke82 that's what we're trying to achieve; getting the cars to alter their speeds based on curvature and grade of road.

So users might have road that is 60MPH, but due to bends (in particular) and grade, some parts of the road might require vehicles to reduce their speed. We could potentially also create some sort of info view showing red where traffic has to go slower than current speed limit and green where potentially traffic could go faster than current speed limit.

The benefits are:

* More realistic motion of traffic
* Less need to micromanage speed limits
* Discourage "cheats" like using fast highway roads for roundabouts
* Visualise effect of road curvature on an info view (hopefully)

**Comment by Sipke82** [comment]
Well when watching this with the FPS camera mod (which displays the actual speed) Vehicles do slow down in the corners.. Personally i think its still a bit fast :-S

![image](https://user-images.githubusercontent.com/30873812/80129242-1493ae00-8597-11ea-8f25-fdd34a39cb4a.png)

**Comment by kianzarrin** [comment]
Does everyone agree that shift clicking roundabout should change the speed of the whole roundabout rather than until junction?

> @thebugfixnet I figured out that the Speed-Limit function works within round-abouts in the same way they do on normal roads.
On normal roads with Shift-Klick the speed limit is assigned from one junction to the next. I can understand this as in real world also the speed limits at the next crossing may be different. So this behavior i was ecpexting.
But on roundabouts in my opinion there should be the logic to set the speed limit for the whole roundabout street with Shift-Klick. This is the way ot is in real i think. Additionally the super function of automated lower speed limits on roundabouts do it for the whole roundabout road. To be consistend to this function it would be good to handle it in the same way for the speed-limit function.
![image](https://user-images.githubusercontent.com/37211016/80286843-15ab1380-872e-11ea-85bf-0daee860336f.png)

**Comment by aubergine10** [comment]
It should, and it should set the speed to whatever the user has selected.

To adjust speed based on curvature/grade, that should be buff/nerf done automatically if possible.

**Comment by kianzarrin** [comment]
created issue #869  for speed limit tool to cover the roundabout.

**Comment by scottmcm** [comment]
Thanks, folks!  I'm excited to try this when 11.6 comes out!

**Comment by kianzarrin** [comment]
@Biffa:
Next TMPE version will be able to setup REALISTIC roundabout speed limit based on the size of the roundabout (sharp curves means lower speeds). It will be turned off by default but you can change it via the policy tab in mod settings.

Additionally you can shift click to change the speed of the whole roundabout (#869) (Control+shift+click for lane wise):
![image](https://user-images.githubusercontent.com/26344691/83518480-298f2580-a4e3-11ea-9c17-f110c6d77c2c.png)

I am not so sure if reducing roundabout speed (but I could be wrong will reduce traffic. We are adding these options for the sake of realism.

You mentioned in your videos that reducing roundabout speeds can give cars a chance to get in and reduce traffic. I noticed that after reducing roundabout speed, you did not came back to check if you got any improvement (unless if you cut that part out). I tried this my self and I observed that reducing roundabout speed actually decreases traffic flow and increase traffic jams ( I am a fallible being so I can make mistakes!):
- Pro: as you said in your video, decreasing speed decreases the safe distance (see image bellow) from upcomming car (on the roundabout) for cars to join the roundabout.
![image](https://user-images.githubusercontent.com/26344691/83520679-bb4c6200-a4e6-11ea-8cab-276f60ec3c6f.png)
- Con: but it also means that it takes longer for the cars on the roundabout to leave get out of the way so that cars can join the roundabout. This cancels out any advantage you gain from the "Pro" above.
- Con2: At the end of the day, the faster cars move on the roundabout, the more throughput it has, and the more cars it can let through.

Going slower on the roundabout does reduce car accidents (and hence traffic jams) in the real world but considering that there is no accidents in Cities skylines, higher speed is a risk free advantage.

Anyway just my opinions and I could be wrong so I like to know your thoughts on this as well.

**Comment by kianzarrin** [comment]
Biffa In your videos you like to enable lane switching at the the entrance of the roundabout:

![image](https://user-images.githubusercontent.com/26344691/83538002-fefe9600-a4fd-11ea-817f-29b2f4b04bd1.png)

as you can see from the image above, if cars lane switch at the roundabout, they are going to get in the way of the cars that are already on the roundabout as well as the cars joining the roundabout on that road.

But if the cars switch lane before arriving at roundabout then they only get in the way of the cars on that road. Which is not a big deal because in on a busy roundabout the cars have to wait before they can enter the roundabout anyway.
![image](https://user-images.githubusercontent.com/26344691/83538553-9ebc2400-a4fe-11ea-86f3-afc8d00de023.png)

When I tried turned on the "Vehicles going straight on may change lanes at junctions" on the roundabout, it had no influence ... probably because cars are not going straight but rather are turning right into the roundabout.

If the highway rules are enabled, its a different story though. If highway rules is enabled (not recommended) and highway roads joins a highway roundabout then you MUST turn on lane switching when entering the roundabout or cars will not use the outer lanes of the roundabout anymore. For this reason my TMPE roundabout auto-setup silently activates the lane changing rule at such circumstances.

**Comment by DaEgi01** [comment]
> * Con: but it also means that it takes longer for the cars on the roundabout to leave get out of the way so that cars can join the roundabout. This cancels out any advantage you gain from the "Pro" above.
> * Con2: At the end of the day, the faster cars move on the roundabout, the more throughput it has, and the more cars it can let through.

This is not true if you consider that safety distance does not increase linearly with speed, at least IRL. No idea what the formula is ingame.

**Comment by kianzarrin** [comment]
@DaEgi01 You make a very good point. Safety distance increases as a power of two (I guess) but getting out of the way is directly proportional to speed. (assuming TMPE implementation matches reality).

There are many factors in play like a faster roundabout gets cleared faster allowing cars to come in. When I tried it in game several times, every time when I reduced roundabout speed traffic started to build up. when I increased roundabout speed, traffic got cleared. A few samples only so not that much.
