### ISSUE TITLE
Customized Default Speed Limits do not save upon new game start

### ISSUE THREAD

**Issue by A-PENCIL-SHARPENER** [CitiesSkylinesMods/TMPE#804]
Moved from Steam on request.

### Describe the problem

The feature that saves the settings for new default speed limits doesn't work.

### Steps to reproduce

I have no idea how to reproduce this bug because it's a feature in the mod already.

### Log files

https://ufile.io/l2zzwhl7

### Savegame?

It affects the mod itself, not the savegame.

**Comment by aubergine10** [comment]
Hi can you upload the [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/wiki/TMPE.log) file as well - just drag it on to comment box below, wait for it to upload then click comment

Also, if you can [share your save game to workshop](https://github.com/CitiesSkylinesMods/TMPE/wiki/Share-your-Savegame-on-Steam) and send us the URL to it we can test to see if it's specific to your city.

**Comment by aubergine10** [comment]
TM:PE 11.2.1 STABLE

Notable errors:

* `Error: Cannot create FMOD::Sound instance for resource, (Operation could not be performed because specified sound/DSP connection is not ready. )` - see: **[how to fix](https://github.com/CitiesSkylinesMods/TMPE/wiki/No-audio)**
* `Look rotation viewing vector is zero` - graphics card issue?
    * `ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)`
    * Update graphics drivers direct from AMD website
    * Try `-force-d3d9` [launch option](https://steamcommunity.com/sharedfiles/filedetails/?id=466981085) to use less stressful graphics mode

Relevant DLCS:

- After Dark' id: '369150' available: 'true'
- Snowfall' id: '420610' available: 'true'
- Match Day' id: '456200' available: 'true'
- Natural Disasters' id: '515191' available: 'true'
- Mass Transit' id: '547502' available: 'true'
- Green Cities' id: '614580' available: 'true'
- Parklife' id: '715191' available: 'true'

Incompatible Mods:

- Freewalking Mod - _not compatible with First Person Camera mod_
- Control Building Level Up - _possibly outdated, use 'Historic building' feature on builoding info panels, or use 'Historic Districts' mod if you want to apply to whole district_
- Customize It! - _outdated, unsub and replace with Customize It Extended_
- Surface Painter - _reported to have some bugs since Sunset Harbor update, disable?_
- Auto Line Color - _broken, unsubscribe. a newer version is [here](https://steamcommunity.com/sharedfiles/filedetails/?id=1415090282)_
- One-Way Street Arrows - _Obsolete, base game now has this_
- Tree Snapping - _incompatible with Unlimited Trees mod; causes trees to float_
- Ragnarok EXTREME EDITION - _marked as game breaking on broken mods list_
- Tsunami Disaster (Water Spawner) - _possibly incompatible with Ragnarok_
- American Railroad Crossing Replacer - _possibly conflicts with TMPE_
- Roads United Core+ - _Breaks toll booths (prevents them generating income)_
- Building Themes - _can sometimes break save games_
- Open Street Cities - _possibly causing issues depending on how it creates roads_
- Addresses & Names Mod 2.0.1 - _likely to conflict with the CSLNamesMod_
- Klyte's Fine Road Tool 2.0.3 - _minor bug: it's collision toggle feature isn't working currently_
- CSLNamesMod 1.0.0 - _very old mod, might be breaking speed limits, also likely to conflict with Addresses & Names Mod_
- Unlock All + Wonders & Landmarks
- Network Extensions 2 - _minor bug: zoning on tiny roads not working poperly_
- First Person Camera - _not compatible with Freewalking Mod_
- IOperateIt - _possibly incompatible with TM:PE and also First Person Camera and also Freewalking Mod_

**Comment by A-PENCIL-SHARPENER** [comment]
The only thing that it found incompatible on my side was Roads United Core+. As far as I know, the toll booths in my cities have kept generating income, but I can't confirm that.

**Comment by A-PENCIL-SHARPENER** [comment]
Also, for Tree Snapping, you can change whether you want the tress to follow or not to follow the terrain when it's changed. That could fix the problem with floating trees...

**Comment by krzychu124** [comment]
Speed limits manager code has been rewritten in the mean time. It should no longer happen if no conflicts with other mods. Create new issue in case of similar problems.
