### ISSUE TITLE
Issue with all savegames

### ISSUE THREAD

**Issue by BenW40** [CitiesSkylinesMods/TMPE#805]
### Describe the problem
After recently downloading the Industries and After Dark DLCs, I loaded a savegame with TMPE 10.20, where I got the following error message.

Object reference not set to an instance of an object [System.NullReferenceException]

Details:
No details

I closed the game, checked the Workshop for new versions, and unsubscribed from 10.20 whilst subscribing to the latest (as of March 31) version of STABLE (I think it was 11.2). I loaded multiple different savegames, and got the same error message. 

### Steps to reproduce

1. Literally just opening any savegame
2. 
3. 

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4406389/output_log.txt)

[error.log](https://github.com/CitiesSkylinesMods/TMPE/files/4406391/error.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4406392/output_log.txt)

**Comment by aubergine10** [comment]
TMPE 10.20 is obsolete and not compatible with Sunset Harbor game update.

* Exit game to desktop
* Unsubscribe old TMPE: https://steamcommunity.com/sharedfiles/filedetails/?id=583429740
* Subscribe new TMPE v11: https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252

Also, I'd recommend these two mods as well:

* Fixes bug in current game update: https://steamcommunity.com/sharedfiles/filedetails/?id=2037862156
* Tells you if you have old/broken mods: https://steamcommunity.com/sharedfiles/filedetails/?id=2034713132

**Comment by Xyrhenix** [comment]
There's a repeating error at the bottom indicating that you are using assets affected by the IsIntercity bug. You'll need to subscribe to the first of the two mods recommended by Aubergine to alleviate this bug.

TM:PE itself is not erroring in any way, according to the logs you've sent.

The crash you experienced regarding the error.log and associated output_log appears unrelated to TM:PE. It looks as if you straight-up ran out of RAM. Since you only have 8GB of RAM, this isn't completely unexpected. Cities: Skylines is very resource-intensive and eats RAM very quickly.

**Comment by aubergine10** [comment]
This guide might help with the RAM issue (read RAM, Page File and Loading Screen Mod sections): https://steamcommunity.com/sharedfiles/filedetails/?id=465790009

Even then 8GB RAM is not really enough to play modded Cities: Skylines - consider upgrading to 16GB or 32GB RAM.
