### ISSUE TITLE
Parking cars exhibit odd behaviors

### ISSUE THREAD

**Issue by rcepe3241** [CitiesSkylinesMods/TMPE#846]
### Describe the problem

When cars are trying to park they will go through buildings, through fields, fly through the air to get to a parking spot. This occurs on roads that have parking spots and also on parking lots. I do use parking lots quite a bit so not sure if that's an issue; however, with it also affecting vanilla roads with parking, my parking lots may not be a problem. I have not started a new city with my mods turned off, but i've been using TM:PE for over 18 months now and I never saw this behavior until the Sunset Harbor release. I am not using Industries or Sunset Harbor DLCs at this time.

Update, so I turned off TM:PE and loaded my save and I am not seeing the same behavior. I should've done that from the start.  Perhaps it's the parking AI? Idk. Thanks for looking into this!!

### Steps to reproduce

1. Load my city 
2. Just play and watch areas where cars are trying to park on streets. 
3. Cars will float into opposite lanes of traffic, they will block intersections, they will go through open areas and go under or over ground.

### Log files

Attaching output log and tmpe.log

### Savegame?

https://steamcommunity.com/sharedfiles/filedetails/?id=2063426783

### Screenshots?

Did not take any but the save game should show what I'm talking about, if more info is needed like screenshots or videos I can supply.
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4489425/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4489426/output_log.txt)

**Comment by aubergine10** [comment]
This might be the culprit:

![image](https://user-images.githubusercontent.com/1386719/79639540-5fbb5480-8184-11ea-97a6-80ea2dd5928a.png)

line `2644` of `Manager/Impl/AdvancedParkingManager.cs` in the `FindParkingSpacePropAtBuilding()` method

**Comment by Sipke82** [comment]
Would be nice if we can set this parameter in the global xml.
See #298

**Comment by miguelrs** [comment]
Just to give a bit more info, I've been seeing this behaviour without any DLCs at all.  
Now I've got Mass Transit and still have the exact same behaviour.  
I do not have Sunset Harbour.

And as I said in #298 I'm pretty sure this behaviour occurs only (or at least much much more often) with tourists, while local citizens do it just fine, driving to the parking space perfectly 🤷‍♂️ 

I spent a lot of time detailing the suroundings of my train stations to give them a realistic look, but then I see loads of cars going there, that simply start floating through whole blocks of buildings, parks, fields, whatever... in order to park their cars and go to the station... 😞  
Please fix this if you can 🙏 
And again, thanks a lot for the mod - it's really awesome 🏆

**Comment by aubergine10** [comment]
User **xerxesaria** on Steam has same issue:

Log [TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4525190/TMPE.log)
Save: https://steamcommunity.com/sharedfiles/filedetails/?id=2070749526

Apparently even if all other mods disabled, TMPE will cause the issue. I am almost certain that it's due to that `propMinDistance`, however that wouldn't explain what **miguelrs** experienced with mostly tourists exhibiting the issue.

**Comment by rcepe3241** [comment]
I've been playing for the last two hours and I'm not seeing it specifically affecting tourists. It seems to be tourists, exchange students and regular cims.

**Comment by miguelrs** [comment]
@rcepe3241 yeah TBH after writing the previous message I've been taking a look again, and I did see some local cims doing the same thing... 👍

**Comment by aubergine10** [comment]
Ok, that's good to know it's affecting all vehicles as that rules out some demorgaphic-specific chunks of code.

**Comment by miguelrs** [comment]
@aubergine10 yeah I can confirm it happens with all types of cims.  
I've just seen a local cim floating for 413m (using Measure It), across 4 roads and 10 buildings, to park their car 😅 

Also, I can confirm that it seems to happen randomly - there may be 2 cars of the same type of cim, going to the same place, and one of them starts to "levitate" and the other one goes to the correct place to park (you can even see the info tooltip saying it's trying to park and the number of attempts)... I was trying to find a pattern, but I cannot see any - it's just it happens most of the times 🤷‍♂️

**Comment by aubergine10** [comment]
We're currently testing a version of TMPE migrated to Harmony 2.x and one tester mentioned that they've not seen any floating cars in that version.

If you want to test, there's a zip file with updated dlls in the PR: https://github.com/CitiesSkylinesMods/TMPE/pull/866#issuecomment-619546933

**Comment by rcepe3241** [comment]
Ok I'm going to test now

**Comment by rcepe3241** [comment]
I have played the game for over an hour. I'm not seeing leveraging or floating cars. Still seeing cars driving through buildings, driving in the opposite travel lane and through fields to park.

**Comment by aubergine10** [comment]
So it's partially fixed, but there are still some issues?

When they drive in the opposite travel lane, what do you mean by that? Are they literally driving wrong way down a road? Or are they doing a "mini float" to parking on other side of street?

**Comment by rcepe3241** [comment]
Yes I would say it's partially fixed. So yes the car will slowly travel
from say the right lane into the left lane against traffic to then find a
parking spot where it will then turn around and park. When this happens it
will affect oncoming traffic whereas the traffic will slow trying to avoid
the cars trying to park.

**Comment by rcepe3241** [comment]
I spoke too soon. I'm playing this afternoon and saw a car float from the
highway to a nearby street to park.

**Comment by nampas** [comment]
I've been experiencing this issue as well, cars will slowly float from the road to a parking spot on a different road.

@aubergine10 Could you explain (or point me to an explanation) of how parking works with TMPE in general? Since installing the mod a couple days ago there are way more parked cars (which is cool), but they often seem to be parked very far away from the owner.

Thanks for all the hard work on this mod!

**Comment by aubergine10** [comment]
> Could you explain (or point me to an explanation) of how parking works with TMPE in general?

Simple explanation: Not very well. :)

Longer explanation:

We need to rewrite the pathfinder and parking AI. The problem is essentially that the current pathfinder works from building (or node) `A -> B`.

Only when it reaches `B` does it start thinking about parking, and that in itself causes many problems.

To try and make the current pathfinder find parking prior to reaching `B`, it would mean at least 2 paths per vehicle: `A -> Parking -> B`.

But if there's no parking, then the `A -> Parking` needs repeating. So a quicker way is to start from `B` and look for nearby _reachable_ parking, ie: `B -> Parking`.

But then that parking needs to be reachable from `A` (pathfind: `A -> Parking`), and if it isn't we need to start with another set of parking near destination and try again: `B -> Parking (that hasn't already been tried)`.

Rinse, wash, repeat.

That description is still overly simplified heh. There's parking grids, spiral loops and all sorts of other stuff lurking in the spaghetti of trying to find cims a good parking space. It just turns in to a laggy can of worms, which is why it's taking us so long to solve.

**Comment by rcepe3241** [comment]
Thanks for what you're doing!
