### ISSUE TITLE
Vehicles stopping at nodes between different segments.

### ISSUE THREAD

**Issue by wetpavement** [CitiesSkylinesMods/TMPE#862]
### Describe the problem

Cars treat nodes between two different segments as either a stop sign, or an intersection that cannot be entered if blocked. Trying to enable/disable traffic lights or stop signs using the vanilla options in the junctions tab does not work, icons do not appear. Enabling/disabling stop signs with TM:PE is ineffective. Changing junction rules with TM:PE is ineffective. Enabling traffic lights at the node with TM:PE solves the issue but introduces an unnecessary traffic light.

### Steps to reproduce

1. Build a length of road
2. Upgrade some segments on that road to some other type
3. Unpause the simulation and let traffic flow. The node at which the two different segments meet should have traffic stopping

### Log files

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4524760/output_log.txt)
[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4524762/TMPE.log)

### Savegame?

Unable

### Screenshots?

![Screenshot 329](https://user-images.githubusercontent.com/64221749/80140983-c40c5880-8576-11ea-81f1-e93e06c3bdbe.png)
Cars stopping where two-lane one way meets large tram avenue.
![Screenshot 338](https://user-images.githubusercontent.com/64221749/80141032-df776380-8576-11ea-828b-df16e8def446.png)
Cars stopping where segment changes.
![Screenshot 339](https://user-images.githubusercontent.com/64221749/80168781-c4761500-85b1-11ea-95ca-c2f67f3ae2b0.png)
Entering blocked intersection allowed.
![Screenshot 340](https://user-images.githubusercontent.com/64221749/80168786-c8099c00-85b1-11ea-9dd0-3ac367a44839.png)
No signs.
![Screenshot 341](https://user-images.githubusercontent.com/64221749/80168791-cb048c80-85b1-11ea-95b7-9bb6110c7e41.png)
Nodes aren't highlighted when hovered over in vanilla junction properties, mouse isn't in screenshot but is over the node.

### Notes or questions?

Savegame has been through a lot and is running many mods, behaviour could be caused by an unknown mod conflict or could be another mod entirely. Thanks for the help :)

**Comment by aubergine10** [comment]
Is it only happening on CSUR roads?

@pcfantasy have  you noticed any issue like this?

**Comment by pcfantasy** [comment]
@wetpavement 

Never meet this problem.

And for if a node is connected with a CSUR offset road.  CSUR toolbox remove junction flag for this node, so there will be no traffic light no junction rule ....   not TMPE`s fault.

But anyway, cars will not stop for a while in that junction.

You can raise a issue in CSUR toolbox`s github, I will check this if I meet the same issue, thanks for the feedback.

**Comment by wetpavement** [comment]
> Is it only happening on CSUR roads?
> 
> @pcfantasy have you noticed any issue like this?

No, it happens on other road types as well. The first screenshot is the vanilla two-lane one-way road and a tram avenue from the workshop

**Comment by wetpavement** [comment]
UPDATE: Found more on the issue- the stopping cars on CSUR roads was because I had that road labelled as a priority road. Unchecking the radio button fixed that. However, the same fix doesn't seem to be working for osm intersections between non-CSUR roads. The first screenshot, for example, apparently has a vanilla stop sign (didn't notice it at first), but it's impossible to remove because the vanilla junction editor doesn't let me select any nodes.

**Comment by shadertheboi** [comment]
I am also facing the same issue as TS. Vehicles would "top at all junctions as if there is a "stop" sign and then move on. The only remedy for this issue that I found out is also only adding an unneeded traffic light at the junction and setting that traffic config to show the "green light" infinitely.

**Comment by krzychu124** [comment]
Another cause might be near 0 length segment. It happen sometimes when you use Node Controller or move one node to close to the other with MoveIt

**Comment by shadertheboi** [comment]
> Another cause might be near 0 length segment. It happen sometimes when you use Node Controller or move one node to close to the other with MoveIt

I don't think so...? I dunno..

But here's a short clip of the mentioned bug...

https://imgur.com/gallery/OyPx1b8

**Comment by shadertheboi** [comment]
![image](https://user-images.githubusercontent.com/59530097/99525730-2cb89800-29d5-11eb-9fac-54aaac5d415e.png)
 Another example of another junction (3-way)

**Comment by shadertheboi** [comment]
[https://imgur.com/gallery/XEInsDR](url)

Okay, I found out that by changing all roads in the said junction to highway roads eliminates this problem.

But kinda strange that this happens with other roads; particularly the smaller roads.

**Comment by krzychu124** [comment]
Hi, I checked that clip https://github.com/CitiesSkylinesMods/TMPE/issues/862#issuecomment-729615672 and first thing I noticed is that road which goes straight has wrong lane arrows. I don't know why.
The other screenshot also looks weird https://github.com/CitiesSkylinesMods/TMPE/issues/862#issuecomment-729621869 Normally if you create lane connection, lanes are connected 1:1, transitions between unconnected lanes are impossible for pathfinder. 
I assume there must be a bug somewhere. If you have that savegame from the clip somewhere, I would like to check what lane transitions were calculated for that bugged intersection. 

I did a lot of tests of current pathfinder and it seems that there is something wrong with lane arrows (probably that's why users are using lane connections everywhere). Vehicles simply ignore them even at most strict restriction settings.

Regards to lane connections from clip, if you are connecting two 2-lane segments into 4-lane segment you shouldn't need lane connections because routing table should calculate it automatically for you, exactly how you connected it. Something is wrong there.
BTW, do you use [highway rules](https://tmpe.viathinksoft.com/wiki/index.php?title=Highway_rules) feature?

**Comment by shadertheboi** [comment]
Nope, I don't use the highway rules feature. Hence, I am able to manually plot the lane connectors on highways. Lol

Previously, every time when I build new roads, I would mostly not reconfigure the junctions, arrows, traffic lights and whatnot until realtime traffic flows through the junction, only basic reconfiguration of the lights to smoothen out traffic flow which is always done during morning peak hours as I believe this period can garner the truest traffic data amongst other time periods.

Now, I've become more meticulous in planning out junctions, especially main boulevards where bottlenecks are inevitable but clearable with time during peak hour traffic. Most of the time, traffic is the key determinant of the reconfiguration of any junction.

> The other screenshot also looks weird [#862 (comment)](https://github.com/CitiesSkylinesMods/TMPE/issues/862#issuecomment-729621869) Normally if you create lane connection, lanes are connected 1:1, transitions between unconnected lanes are impossible for pathfinder.
> I assume there must be a bug somewhere. If you have that savegame from the clip somewhere, I would like to check what lane transitions were calculated for that bugged intersection.

I'll post a short clip to demonstrate how these arrows are generated and I'll post my savegame as well after that.
Give me a moment.

**Comment by shadertheboi** [comment]
https://imgur.com/gallery/Vjg5cvL
https://imgur.com/gallery/UWfEQqE

The first video shows how the lane arrows change using the manual lane connector tool.
The second video shows how the lane arrows change via shifting and bending roads.

As shown in the videos, if the manual lane connector tool is not used, it can be hard to determine if a certain lane is directing traffic to the indented roads. 
For example, in the first video, traffic from Eu Tong Seng Street travelling eastwards, I would set the lane arrows to "straight" instead of "left" as proven by the manual lane connector tool. And for complicated road junctions like this one, there is really no way(I've tried) to position the roads in a way that correctly corresponds to the lane arrows.

The second video shows just how the lane arrows are changed by shifting the roads using "Touch! it". So for complicated road junctions like these, manual lane connector tool is always my best bet.

**Comment by krzychu124** [comment]
Fundamental question: do you have _Simulation Accuracy_ setting on **Very High**? It directly affects how vehicles treat priority signs, if set lower than **High**, they can start ignoring settings to save performance - it's pretty demanding on CPU, raises along with road congestion rate, because of increased number of _test vehicle has priority_.

Without savegame there is not much I can do. You can share it on steam, or dropbox or whatever.

**Comment by shadertheboi** [comment]
Oh yes! I recently set it to **Very High**! LoL! Oops! 

I guess I'll set it back down to medium then...

**Comment by krzychu124** [comment]
I mean, by setting it lower than **Very High** expect that vehicles will start ignoring yield or stop signs you've set at intersection, so in this case **Very High** is OK. If they still stop before entering, check for vanilla priority road settings and also make sure there are no vanilla stop signs.

**Comment by shadertheboi** [comment]
> Another cause might be near 0 length segment. It happen sometimes when you use Node Controller or move one node to close to the other with MoveIt

Okay, I just found out today from one of my roundabouts that this is also another factor that is causing this issue too. I didn't notice this issue on the roundabouts in my city prior, strangely.

**Comment by krzychu124** [comment]
Yes, it's very hard to spot. You can use TM:PE node overlay to check if there are overlapping nodes or not (blue text)

**Comment by krzychu124** [comment]
Reading the comments it seems to be solved. Closing.
