### ISSUE TITLE
Add Unofficial.Microsoft.Unity.Analyzers

### ISSUE THREAD

**Issue by aubergine10** [CitiesSkylinesMods/TMPE#916]
Trying to add the `Unofficial.Microsoft.Unity.Analyzers` to TLM project but getting this error:

![image](https://user-images.githubusercontent.com/1386719/83340304-57e7e780-a2ce-11ea-9ae7-c193a3f248c8.png)

**Comment by DaEgi01** [comment]
Issue is that SkyTools want a specific version of Harmony 1.2.0.1 but TMPE references 2.0.9.0.
Under normal circumstances this would cause issues so harmony warns about that.
But we have no normal circumstances due to the crazy stuff that happens at runtime ;D
So you have to tell nuget to ignore that issue when you install that new package.
Once you have the package selected, open the "options" in the right window, select "Dependency behavior: Ignore Dependencies". That should add the package without issues..

**Comment by aubergine10** [comment]
I suspect `null` issues are behind the crashes on Linux #817 ...

Tried disabling the dependency checks but now I get this error:

![image](https://user-images.githubusercontent.com/1386719/83660544-e0ab9f80-a5bc-11ea-84e7-cea1bf885d13.png)

If someone is able to add the package, please do as we need to start tracking down the bad null checks.

**Comment by DaEgi01** [comment]
had no issues adding the package.
see https://github.com/CitiesSkylinesMods/TMPE/pull/922.

**Comment by DaEgi01** [comment]
now I removed ~100 warnings but added 1500 new ones ... awesome XD
