### ISSUE TITLE
Parking AI gets very confused in large parking lots

### ISSUE THREAD

**Issue by TanerH** [CitiesSkylinesMods/TMPE#924]
### Describe the problem
Using the "Big Parking Lots" road assets (https://steamcommunity.com/sharedfiles/filedetails/?id=2115188517), the parking AI will sometimes get extremely confused, and drive in circles causing huge gridlock - even while there are plenty of spots available.
(I've also noticed the AI seems to try to always park in a certain area of the lot - perhaps circling many times - even though there are plenty of open spaces, overall)

### Steps to reproduce

1. Subscribe to BPL assets (https://steamcommunity.com/sharedfiles/filedetails/?id=2115188517)
2. Enable TMPE Parking AI
3. Set up a parking lot near something that will have lots of traffic (Metro/Rail depot, for example)

### Log files

Not sure which types of logs you'd like, as this wasn't really an "error", but just seems to be an issue with how the simulation runs.

### Savegame?

I can get you a saved game if you want, but this happens in all sorts of situations for me.  It's pretty straightforward to set up a large parking lot near an asset that has high parking demand.

### Screenshots?

https://i.imgur.com/U1xbjxB.jpg

### Notes or questions?
I have briefly corresponded w/ the BPL author, but I don't think there's anything he can do to influence how the Parking AI behaves, but if there is, I can relay that to him (I will also send him the link to this GitHub Issue)

**Comment by s2500111** [comment]
Seems to happen with any larger parking lot ...
Loads of empty spaces but still they circle around.

![20201231003049_1](https://user-images.githubusercontent.com/11500068/103386537-92815f00-4aff-11eb-8605-ebd995690644.jpg)

**Comment by db48x** [comment]
It took this guy two attempts to park: http://db48x.net/temp/parking%20ai%20bug-2021-01-08_02.03.13.mkv

**Comment by db48x** [comment]
I haven't tried this with BPL yet, but here's a funny one that took 10 tries to park, passing open parking spots each time: http://db48x.net/temp/parking%20ai%20bug-2021-01-09_00.11.12.mkv

I took a look at the source code, and while I cannot claim to fully understand even just the parking AI, the randomization of which parking spots are acceptable is my first guess about the cause of this. I think that after failing to find a parking spot by that method, the AI should do a linear search along the current road to find open parking spots, with no randomization. This would ensure that after failing to find a spot on the first try, most vehicles simply take the next available spot in the direction they are currently travelling.

**Comment by krzychu124** [comment]
> I think that after failing to find a parking spot by that method, the AI should do a linear search along the current road to find open parking spots, with no randomization.

Yes, that would be the best, but problem is there is no code for that and PathFinder in not designed for it (simply takes start and end position and some other attributes but linear search is not possible with the current implementation). 

There are three types of parking spaces.
- building parking space - e.g. parking props placed in the area of residential building
- parking building - similar to building parking space - parking props placed inside of the building
- road side parking - there are no parking space props, every parking location must be calculated dynamically by trying to fit vehicle on the parking lane.

The real problem with speed of searching for parking space is we don't have lookup table with parking spaces. 
We need to select building and then check if there are parking spots and then check if any is not used. 
For roadside parking space is even worse because we have to scan each lane to check if it can fit the vehicle. Obviously one vehicle may fit, the other might be too long/wide(rare) :/ 
Parking prop alone has no info in which building was placed and which roads has access(is connected) so its:
- Road -> Building -> Parking prop
- Road -> Parking lane -> scan lane if fits vehicle

There is no quick way to go other way around other than brute force scanning area for building with that prop.

When you see circle on the path it's the end of the path where searching for path should begin. There is no additional path which vehicles could follow while we are searching for parking space. The only thing we know at that point is position of target

More info about ParkingAI https://github.com/CitiesSkylinesMods/TMPE/issues/551

**Comment by db48x** [comment]
I haven't read all of the code yet, but it seems to me that it should be possible to implement even if the current Pathfinder or parking manager doesn't support it yet. I think that all it would require is to know what segment the current car is on, its position within that segment and direction of travel, what buildings have their entrance on that segment, and what segments it connects to. It's possible of course that some of this information is impossible or difficult to get access to.

Using that information, I would do a quick search of the current segment and any segments reachable through the next intersection for parking spots, both in buildings and in parking lanes. There would be no randomization, as the driver is simply going to accept the first parking spot they find. If that fails, I would fall back to the current behavior.

Unfortunately I'm not sure that will be able to implement it myself. I don't use Windows, so I can't simply install Visual Studio and the C# compiler and try it out. TMPE doesn't appear to already have a build system set up using an alternative, such as Mono, and that would be a rather large yak to shave.

**Comment by krzychu124** [comment]
Yeah, I get your idea. I will check what can be done. 

I was already thinking about creating simplified version of PF which would work almost exactly as you described but run the search on the separate thread(with queue). Parking space lookup dictionary, segment oriented, could really speed it up.

Remaining question are: 
- when start searching
- how to prevent vehicle from despawning if reach the end of the path

BTW, in case you want try [BUILDING_INSTRUCTIONS](https://github.com/CitiesSkylinesMods/TMPE/blob/master/docs/BUILDING_INSTRUCTIONS.md) Build target .net 3.5

**Comment by db48x** [comment]
Searching the current segment and it's neighbors should be doable inside the current frame time, even if many cars are failing to park on the same frame. This would simplify the implementation, with no need for a queue or synchronization with another thread.

**Comment by krzychu124** [comment]
Yes, I can easily get segment, lane and position on that lane from current PathUnit and then move to the next segment via either its start or end node (node can connect up to 8 segments), so that could be pretty easy to search for roadside parking space.

There is a problem with buildings. Building structure does not store info about connected segment(s) and vice versa and also no info about neighbor buildings.
Buildings are added to the building grid _(sort of linked list, `m_nextGridBuilding` field stores ID of next building or 0 if is the last one)_, building grid has resolution 270x270, map is ~17k x 17k (f), cell side has 64f.

I need to calculate correct grid cell _(segment are added to the segment grid with the same resolution as buildings)_, e.g. using segment position and then loop through all buildings of that "list", not guarantee then are connected to road accessible from vehicle position. 
Not to mention that there must be walking path between parking spot and citizen target position(e.g. home, work building).

**Comment by db48x** [comment]
> There is a problem with buildings. Building structure does not store info about connected segment(s) and vice versa and also no info about neighbor buildings.

Oh, that makes it more annoying. Seems pretty unusual, since the game is quite insistent about giving every building road access. I guess I can't offer much advice there, but would it possible to maintain a mapping from segments to buildings? That is, every time a segment or building is added or removed, store that information to be accessed later? Either way, it sounds like you already have a handle on it.
