### ISSUE TITLE
Why ShipAI alone does not have skipQueue

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#952]
@krzychu124 did you forgot to add skipQueue to ShipAI?
If so we should delete this line:
```c#
//CreatePathPatch.cs
if (ai is ShipAI) args.skipQueue = false; // TODO [issue #952] why ShipAI should be different than others?

```
If not we should add a comment there explaining why.

**Comment by krzychu124** [comment]
Just in case you don't know: all code changed before Jan 2019 is not mine. It's pointless to ask me about it, because most of the times I would have to respond: don't know.

It's easy to figure out why it's false here (same as vanilla). Path recalculation due to segment change is not the problem here because ships follow invisible line dedicated for ships == no despawn risk.

**Comment by kianzarrin** [comment]
Ships do need to wait in a queue some times to get to the dock.
Then what about Airplanes? They also are like ships.

Actually we have not customized aircraft AI.
So why have we customized ShipAI but not aircraftAI?

**Comment by krzychu124** [comment]
Wait... skipQueue was not changed (for other types) to speed up searching for path, but for fixing problem with despawning, because every time you touch segment or node (changing restriction and other things) segment is invalidated, so without skipQueue, those vehicles (driving through invalidated segments) could despawn before they get corrected path again. In vanilla there are not such problems because invalidation occurs only when you remove or add segment/node (despawn  is not surprise).

We don't have any restrictions for aircraft or ship lines, so I don't think we need to change anything there

**Comment by kianzarrin** [comment]
I see. But why ShipAI has customization but AircraftAI does not?

**Comment by aubergine10** [comment]
Maybe it would help to group things in to "meta" network categories, and then seek consistency within each meta category?

* Dynamic: No fixed network (eg. helicopters)
* Flexible: Easy to reroute (eg. road vehicles)
* Limited: Difficult to reroute, but feasible (eg. ships, aircraft)
* Rigid: Extremely difficult to reroute (eg. tracked vehicles)

The frequency at which users alter networks is influenced by those same factors, which determines the importance of repathing already-spawned vehicles.

I assume failing to repath a vehicle leads to despawning. So on things like ship and plane routes it could be problematic if we try repath too soon?

**Comment by kianzarrin** [comment]
@aubergine10 see also  #954.

Limited: Difficult to reroute, but feasible (eg. ships, aircraft)

I think aircraft is like a helicopter. They are dynamic, aren't they?

**Comment by aubergine10** [comment]
Aircraft is half-dynamic I think. Specifically, maps with air connections have routes drawn on them (the yellow routes if you have More Network Stuff mod and open Aircraft transport tab). However, the link between the yellow routes and the actual airport is dynamic.
