### ISSUE TITLE
Problem with installing a mod

### ISSUE THREAD

**Issue by nedas-sim** [CitiesSkylinesMods/TMPE#968]
### Describe the problem

On Steam workshop I'm trying to get the TM:PE mod, for it I need to get Hide TM:PE Unconnected tracks mod, for which I need the original TM:PE mod. So I get this infinite loop and because of it, I can't install the mod. Is there any way to fix this?

### Steps to reproduce

1. 
2. 
3.

**Comment by Xyrhenix** [comment]
As of the time of checking, TM:PE Labs lists Hide Unconnected Tracks as a dependency, and Hide Unconnected Tracks lists Labs as a dependency. I'm not sure where the bug is here?

![image](https://user-images.githubusercontent.com/39814064/85951018-40952c00-b958-11ea-9dc2-44474e2619f6.png)

![image](https://user-images.githubusercontent.com/39814064/85951024-4be85780-b958-11ea-9eeb-acaff250bcb2.png)

**Comment by krzychu124** [comment]
I also don't see the problem. 
If you want to subscribe item X and that item needs items Y and Z to work, but item Z also need item X to work, subscribing to X will fulfill item Z dependency automatically if you skip subscribing X(you already trying to do it, obviously). Just skip subscribing X, it's pointless because you started whole loop there.

**Comment by nedas-sim** [comment]
Thanks for your help, I got everything going!
