### ISSUE TITLE
Despawning vehicles, stuck vehicles, and vehicles not following lane connection instructions

### ISSUE THREAD

**Issue by friedrice01** [CitiesSkylinesMods/TMPE#979]
### Describe the problem
I recently opened a city that I created on my macbook on my windows rig and now whenever I upgrade a road segment or create new road segments cars will despawn or stop right before the new segment and not move. I also cannot create bus routes over these new segments. If I close the game and reopen it will sometimes resolve itself but then if I make any changes to lane connections or signs it happens all over again, usually in multiple spots. I am also having an issue where at a few nodes vehicles are ignoring specific lane connections and doing whatever they want. It is happening in the roundabouts and highway near my cargo port and cruise terminal.

In the specific instance I have uploaded the saved city and logs for, earlier I downgraded a section of highway leading into the roundabout form 3 lane to 2 lane and had the issues. I saved and quit the game and came back a couple hours later and reopened it and it was fixed. Just to replicate the issue I fixed my lane connections and the lanes were being ignored. Then I added an off-ramp and right back on and suddenly all vehicles going to the highway were either stuck other places or despawning. Screenshots and the saved game are attached. Let me know if I can provide anything else.

### Steps to reproduce

1. Upgrade or downgrade road segment, or delete and recreate road segment
2. Cars stop or despawn
3. In other nodes nearby cars then stop following lane connections.

### Log files

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4941108/TMPE.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4941110/output_log.txt)

### Savegame?

First Save:
https://steamcommunity.com/sharedfiles/filedetails/?id=2169755245
Second save after recreating the issue:
https://steamcommunity.com/sharedfiles/filedetails/?id=2169766250

### Screenshots?

![Screenshot (17)](https://user-images.githubusercontent.com/68455642/87845326-21b0f800-c87b-11ea-878a-0bbe02ae5da7.png)
![Screenshot (18)](https://user-images.githubusercontent.com/68455642/87845328-237abb80-c87b-11ea-95f0-c45e072cdcf4.png)
![Screenshot (19)](https://user-images.githubusercontent.com/68455642/87845356-59b83b00-c87b-11ea-9f07-5f37129b99b8.png)

**Comment by krzychu124** [comment]
Issue is well known and I think you probably didn't noticed pinned issue (there is solution for that in first post)
![image](https://user-images.githubusercontent.com/19638970/87861545-8a65a680-c947-11ea-80c4-24e3c4e39bbe.png)

**Comment by friedrice01** [comment]
Last night I ran the Node detector and fixed a couple nodes that had not appeared earlier when I was trouble shooting, which appeared to fix the issue. Today I was playing for a couple hours and the same issue started happening after I assigned lane connections on a roundabout. I ran the node detector a few times and it says there are no node issues detected. New game files and screenshots are attached.

I didn't see any other workaround looking through that thread so there's a good chance I'm missing something?

https://steamcommunity.com/sharedfiles/filedetails/?id=2170543745

[output_log.txt](https://github.com/CitiesSkylinesMods/TMPE/files/4942476/output_log.txt)

[TMPE.log](https://github.com/CitiesSkylinesMods/TMPE/files/4942477/TMPE.log)

**Comment by friedrice01** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/68455642/87861610-cf182000-c8fc-11ea-8821-5dc13f5309bb.png)
![Screenshot (20)](https://user-images.githubusercontent.com/68455642/87861612-d3443d80-c8fc-11ea-9676-e1f739f14cc2.png)

**Comment by krzychu124** [comment]
Thanks for reporting.
I will check that 😉 

BTW, have you tried it running TM:PE 11.5 Labs?

**Comment by krzychu124** [comment]
It's problem with your connections on that roundabout.

_Remember, lane connections are strict, they are directly connecting lanes, cannot be omitted unlike lane arrows_

**This guy:**

![image](https://user-images.githubusercontent.com/19638970/87862491-07e1e480-c951-11ea-88cc-7f1ecf7da8b3.png)

**...wants to go there(green circle)**

![image](https://user-images.githubusercontent.com/19638970/87862493-0e705c00-c951-11ea-9ad1-7994d19a9911.png)

**...but it is impossible from lane 1 and 2 (count from the left):**

![image](https://user-images.githubusercontent.com/19638970/87862483-f7316e80-c950-11ea-888d-5a00b2f3ad43.png)

**...since vehicles can change lanes only on nodes (white cirles):**

![image](https://user-images.githubusercontent.com/19638970/87862702-61e3a980-c953-11ea-9dc7-900142fe9efe.png)

**...your setup makes two inner lanes of roundabout circling forever, because there is no single node where they could change lane to exit roundabout.**

![image](https://user-images.githubusercontent.com/19638970/87862638-87bc7e80-c952-11ea-8690-cd131d810b6a.png)

- green - circle forever
- blue - only straight, because at next intersection it will be merged with gree
- violet - only right or straight

**Comment by friedrice01** [comment]
I'm a clown and that makes sense. Sorry!

Thanks for taking a look!
